#ifndef DSTATIC_H
#define DSTATIC_H
//--------------------------------------------------------------------------//
//                                                                          //
//                               DStatic.h                                  //
//                                                                          //
//                  COPYRIGHT (C) 1998 BY DIGITAL ANVIL, INC.               //
//                                                                          //
//--------------------------------------------------------------------------//
/*
    $Header: /Conquest/App/DInclude/DStatic.h 76    9/13/01 10:02a Tmauer $
*/			    
//--------------------------------------------------------------------------//

#ifndef DBASEDATA_H
#include "DBaseData.h"
#endif

#ifndef GT_PATH
#define GT_PATH 32
#endif

//--------------------------------------------------------------------------//
//
namespace STTXT
{
enum STATIC_TEXT
{

  NO_STATIC_TEXT		= 0,
  TEST					= IDS_TEST_BUTTON_TEXT,
  PLAYER_NAME			= IDS_ENTER_PLAYER_NAME,
  IP_ADDRESS			= IDS_ENTER_IP_ADDRESS,
  SESSION_NAME			= IDS_ENTER_SESSION_NAME,
  CONFIRM_QUIT			= IDS_CONFIRM_QUIT,
  TITLE_SELECT_GAME		= IDS_TITLE_SELECTGAME,
  PLAYER				= IDS_STATIC_PLAYER,
  SESSION				= IDS_STATIC_SESSION,
  ENTER_TEAM			= IDS_ENTER_TEAM,
  ENTER_RACE			= IDS_ENTER_RACE,
  ENTER_COLOR			= IDS_ENTER_COLOR,
  SELECTED_MAP			= IDS_SELECTED_MAP,
  CHATBOX				= IDS_STATIC_CHATBOX,
  GAME_PAUSED			= IDS_GAMEPAUSED,
  INGAME_TITLE			= IDS_IGOPTIONS_TITLE,
  OPTIONS				= IDS_STATIC_OPTIONS,
  GAMETYPE				= IDS_STATIC_GAMETYPE,
  GAMESPEED				= IDS_STATIC_GAMESPEED,
  CURSOR_SENSITIVITY	= IDS_CURSOR_SENSITIVITY,
  ARTIFACTS				= IDS_STATIC_ARTIFACTS,
  MONEY					= IDS_STATIC_MONEY,
  RESEARCH				= IDS_STATIC_RESEARCH,
  MAPTYPE				= IDS_STATIC_MAPTYPE, 
  MAPFILE				= IDS_STATIC_MAPFILE,
  MAPSIZE				= IDS_STATIC_MAPSIZE,
  TERRAIN				= IDS_STATIC_TERRAIN,
  STATIC_RESOURCES		= IDS_STATIC_RESOURCES,
  WARNBOOT				= IDS_HELP_WARNBOOT,
  SOLOGAME				= IDS_HELP_SOLOGAME,
  LOADGAME				= IDS_STATIC_LOADGAME,
  SAVEGAME				= IDS_STATIC_SAVEGAME,
  FILENAME				= IDS_STATIC_FILENAME,
  FLEET_SIZE			= IDS_FLEET_SIZE,
  SKILL					= IDS_FLEET_SKILL,
  BONUS					= IDS_FLEET_BONUS,
  DUMMY_MONEY			= IDS_DUMMY_MONEY,
  DUMMY_NAME			= IDS_DUMMY_NAME,
  SHIPCLASS				= IDS_IND_SHIPCLASS,
  HULL					= IDS_IND_HULL,
  SUPPLIES				= IDS_IND_SUPPLIES,
  ARMOR					= IDS_IND_ARMOR,
  ENGINES				= IDS_IND_ENGINES,
  WEAPONS				= IDS_IND_WEAPONS,
  SHIELDS				= IDS_IND_SHIELDS,
  KILLS					= IDS_IND_KILLS,
  UNITS					= IDS_STATIC_UNITS,
  INGAME_CHAT			= IDS_REQUEST_CHAT,
  MISSION_OBJECTIVES	= IDS_MISSION_OBJECTIVES,
  END_MISSION			= IDS_END_MISSION,
  SCOREBOARD			= IDS_SCOREBOARD,
  SCORE					= IDS_SCORE,
  VOLUME				= IDS_VOLUME_CONTROL,
  MUSIC					= IDS_MUSIC,
  EFFECTS				= IDS_EFFECTS,
  COMMS					= IDS_COMMS,
  NETCHAT				= IDS_NETCHAT,
  TOOLTIPS				= IDS_TOOLTIPS,
  STATUS_TEXT			= IDS_STATUSTEXT,
  FOGOFWAR				= IDS_FOG,
  MAPROTATE				= IDS_MAPROTATE,
  ROLLOVER				= IDS_ROLLOVER,
  SLOW					= IDS_GAMESPEED_SLOW,
  FAST					= IDS_GAMESPEED_FAST,
  GAMMA					= IDS_GAMMA,
  WEAPON_TRAILS			= IDS_WEAPON_TRAILS,
  EMMISIVE_TEXTURES		= IDS_EMMISIVE_TEXTURES,
  LOD					= IDS_LOD,
  TEXTURES				= IDS_USE_TEXTURES,
  BACKGROUND			= IDS_DRAW_BACKGROUND,
  DEVICES				= IDS_HARDWARE_DEVICES,
  ENTER_NAME			= IDS_ENTER_NAME,
  CAMP_SELECT			= IDS_SELECT_CAMPAIGN,
  SINGLE_PLAYER			= IDS_SINGLE_PLAYER,
  MULTI_PLAYER			= IDS_MULTI_PLAYER,
  FRONT_OPTIONS			= IDS_OPTIONS,
  SKIRMISH				= IDS_STATIC_SKIRMISH,
  INTRO					= IDS_STATIC_INTRO,
  SELECT_MISSION		= IDS_SELECT_MISSION,
  RIGHTCLICK			= IDS_RIGHTCLICK,
  SUBTITLES				= IDS_SUBTITLE,
  JOIN					= IDS_JOIN,
  CREATE				= IDS_CREATE,
  ACCEPT				= IDS_ACCEPT,
  SCROLLRATE			= IDS_SCROLL_RATE,
  QUIT					= IDS_QUIT,
  RESOLUTION			= IDS_RESOLUTION,
  ENTER_STATE			= IDS_ENTER_STATE,
  PLAYER_LIST			= IDS_PLAYER_LIST,
  PING					= IDS_PING,
  APP_NAME				= IDS_APP_NAMETM,
  VERSION				= IDS_STATIC_VERSION,
  HELP					= IDS_STATIC_HELP,
  NET_CONNECT			= IDS_NET_CONNECT,
  HARDWARE				= IDS_HARDWARE,
  GAME					= IDS_STATIC_GAME,
  SPEED					= IDS_SPEED,
  MAP					= IDS_STATIC_MAP,
  RESOURCES				= IDS_RESOURCES,
  BRIEFING				= IDS_BRIEFING,
  VISIBILITY			= IDS_STATIC_VISIBILITY,
  DEVICE_CHOICE			= IDS_DEVICE_CHOICE,
  SOFTWARE				= IDS_SOFTWARE,
  MAP_RANDOM			= IDS_STATIC_RANDOMMAPS,
  MAP_CONQUEST			= IDS_STATIC_SUPPLIEDMAPS,
  MAP_SAVED				= IDS_STATIC_SAVEDMAPS,
  HARDWARE_CURSOR		= IDS_STATIC_HARDWARE_CURSOR,
  PRODUCT_ID			= IDS_STATIC_PRODUCTID,
  REGENERATE			= IDS_STATIC_REGENERATE,
  SPECTATORS			= IDS_STATIC_SPECTATORS,
  LOCK_ALLIANCES		= IDS_STATIC_LOCKDIPLOMACY,
  LOCK_SETTINGS			= IDS_STATIC_LOCKSETTINGS,
  ORE					= IDS_STATIC_ORE,
  GAS					= IDS_STATIC_GAS,
  CREW					= IDS_STATIC_CREW,
  ALLIED				= IDS_STATIC_ALLIED,
  DIPLOMACY				= IDS_STATIC_DIPLOMACY,
  NEW_PLAYER			= IDS_STATIC_NEWPLAYER,
  TITLE_UNITS			= IDS_TITLE_UNITS,
  TITLE_BUILDINGS		= IDS_TITLE_BUILDINGS,
  TITLE_TERRITORY		= IDS_TITLE_TERRITORY,
  TITLE_RESOURCES		= IDS_TITLE_RESOURCES,
  TITLE_TOTAL			= IDS_TITLE_TOTAL,
  TITLE_MADE			= IDS_TITLE_MADE,
  TITLE_LOST			= IDS_TITLE_LOST,
  TITLE_KILLS			= IDS_TITLE_KILLS,
  TITLE_CONVERTED		= IDS_TITLE_CONVERTED,
  TITLE_ADMIRALS		= IDS_TITLE_ADMIRALS,
  TITLE_DESTROYED		= IDS_TITLE_DESTROYED,
  TITLE_RESEARCH		= IDS_TITLE_RESEARCH,
  TITLE_CREW			= IDS_TITLE_CREW,
  TITLE_ORE				= IDS_TITLE_ORE,
  TITLE_GAS				= IDS_TITLE_GAS,
  TITLE_JUMPGATES		= IDS_TITLE_JUMPGATES,
  TITLE_PLANETS			= IDS_TITLE_PLANETS,
  TITLE_EXPLORED		= IDS_TITLE_EXPLOREDSYSTEMS,
  LOAD_MISSION_DATA		= IDS_LOAD_MISSION,
  LEGAL_MAINSCREEN		= IDS_LEGAL_MAINSCREEN,
  LEGAL_ABOUT			= IDS_LEGAL_ABOUTBOX,
  NUM_SYSTEMS			= IDS_STATIC_SYSTEMS,
  BATLEMAP				= IDS_BUTTON_MAPTYPE,
  DISABLED				= IDS_DISABLED,
  STATIC_TERRAIN		= IDS_TERRAIN,
  CHAT					= IDS_STATIC_CHAT,
  DIFFICULTY			= IDS_STATIC_DIFFICULTY,
  EASY					= IDS_STATIC_EASY,
  MEDIUM				= IDS_STATIC_MEDIUM,
  HARD					= IDS_STATIC_HARD,
  SHIPS3D				= IDS_SHIPS_3D,
  BANDWIDTH				= IDS_BANDWIDTH
};

enum STATIC_TOOLTIP
{
  NO_TOOLTIP            = 0,
  ORE_TOOLTIP			= IDS_TT_ORE,
  GAS_TOOLTIP			= IDS_TT_GAS,
  CREW_TOOLTIP			= IDS_TT_CREW,
  COMMAND_POINTS		= IDS_TT_CP,
  DISABLED_TOOLTIP		= IDS_TT_DISABLED,

};

enum STATIC_HINTBOX
{
	NO_HINTBOX			= 0,
	ORE_HINTBOX			= IDS_HINT_TEXT_ORE,
	GAS_HINTBOX			= IDS_HINT_TEXT_GAS,
	CREW_HINTBOX		= IDS_HINT_TEXT_CREW,
	CP_HINTBOX			= IDS_HINT_TEXT_CP,
	DISABLED_HINTBOX	= IDS_HINT_TEXT_DISABLED,

};

} // end namespace
//--------------------------------------------------------------------------//
//  Definition file for static controls
//--------------------------------------------------------------------------//

struct GT_STATIC : GENBASE_DATA
{
	char fontName[GT_PATH];
	struct COLOR
	{
		unsigned char red, green, blue;
	} normalText, background;
    char shapeFile[GT_PATH];                        // vfx shape file

	enum drawtype
	{
		NODRAW,
		FILL,
		HASH
	} backgroundDraw;

	bool bBackdraw;
};
//---------------------------------------------------------------------------
//
struct STATIC_DATA
{
    char staticType[GT_PATH];
	STTXT::STATIC_TEXT staticText;         // can also be used for ID
	STTXT::STATIC_TOOLTIP staticTooltip;
	STTXT::STATIC_HINTBOX staticHintbox;
	enum alignmenttype
	{
		LEFT,
		CENTER,
		RIGHT,
		TOPLEFT,
		TENBYSIX,
		LEFTSIX
	} alignment;
    S32 xOrigin, yOrigin;
	S32 width, height;				// if non-zero, override shape bounds
};

#endif
