#ifndef DBHOTKEYS_H
#define DBHOTKEYS_H
//------------------------------------------------------------------------//
/*
	Header file generated by the HotKey editor (jy)
	Original data file: Z:\CQ2\Code\App\Src\DBHotkeys.utf

	$Header: /Libs/dev/Src/Tools/HotkeyEditor/Hklists.cpp 10    3/21/00 4:30p Pbleisch $
*/
//------------------------------------------------------------------------//

#ifdef _ADB

namespace DBHOTKEYS
{
enum HOTKEY
{
	NONE,
	IDH_BUILD,
	IDH_CAMERA_FOLLOW,
	IDH_CAMERA_LIST,
	IDH_DEBUG_EXCEPTION,
	IDH_DEBUG_TEST_KEY,
	IDH_DEC_PLAYER_NUM,
	IDH_DELETE_SYSTEM,
	IDH_EDITOR_MODE,
	IDH_EXPLODE,
	IDH_FORCE_MIGRATION,
	IDH_GAME_SPEED,
	IDH_HIGHLIGHT_ALL,
	IDH_INC_PLAYER_NUM,
	IDH_LIGHTS,
	IDH_NEBULATE,
	IDH_NEXT_CONTEXTMENU,
	IDH_NEXT_TEXTURE,
	IDH_PITCH_DOWN,
	IDH_PITCH_UP,
	IDH_POSTOOL,
	IDH_PREV_TEXTURE,
	IDH_PRINT_OPLIST,
	IDH_ROLL_LEFT,
	IDH_ROLL_RIGHT,
	IDH_ROTATE_WORLD_DOWN,
	IDH_ROTATE_WORLD_UP,
	IDH_SCROLL_DOWN_DB,
	IDH_SCROLL_LEFT_DB,
	IDH_SCROLL_RIGHT_DB,
	IDH_SCROLL_UP_DB,
	IDH_SHOWPARTS,
	IDH_THRUSTDOWN,
	IDH_THRUSTFORWARD,
	IDH_THRUSTLEFT,
	IDH_THRUSTREVERSE,
	IDH_THRUSTRIGHT,
	IDH_THRUSTUP,
	IDH_UNLOAD_TYPES,
	IDH_VIEWSECTOR,
	IDH_VIEW_SYSTEM_KIT,
	IDH_VOLUME_ADJUST,
	IDH_YAW_LEFT,
	IDH_YAW_RIGHT
}; // enum HOTKEY
}  // namespace

#else  // !_ADB

#define IDH_BUILD                               0x00000001
#define IDH_CAMERA_FOLLOW                       0x00000002
#define IDH_CAMERA_LIST                         0x00000003
#define IDH_DEBUG_EXCEPTION                     0x00000004
#define IDH_DEBUG_TEST_KEY                      0x00000005
#define IDH_DEC_PLAYER_NUM                      0x00000006
#define IDH_DELETE_SYSTEM                       0x00000007
#define IDH_EDITOR_MODE                         0x00000008
#define IDH_EXPLODE                             0x00000009
#define IDH_FORCE_MIGRATION                     0x0000000A
#define IDH_GAME_SPEED                          0x0000000B
#define IDH_HIGHLIGHT_ALL                       0x0000000C
#define IDH_INC_PLAYER_NUM                      0x0000000D
#define IDH_LIGHTS                              0x0000000E
#define IDH_NEBULATE                            0x0000000F
#define IDH_NEXT_CONTEXTMENU                    0x00000010
#define IDH_NEXT_TEXTURE                        0x00000011
#define IDH_PITCH_DOWN                          0x00000012
#define IDH_PITCH_UP                            0x00000013
#define IDH_POSTOOL                             0x00000014
#define IDH_PREV_TEXTURE                        0x00000015
#define IDH_PRINT_OPLIST                        0x00000016
#define IDH_ROLL_LEFT                           0x00000017
#define IDH_ROLL_RIGHT                          0x00000018
#define IDH_ROTATE_WORLD_DOWN                   0x00000019
#define IDH_ROTATE_WORLD_UP                     0x0000001A
#define IDH_SCROLL_DOWN_DB                      0x0000001B
#define IDH_SCROLL_LEFT_DB                      0x0000001C
#define IDH_SCROLL_RIGHT_DB                     0x0000001D
#define IDH_SCROLL_UP_DB                        0x0000001E
#define IDH_SHOWPARTS                           0x0000001F
#define IDH_THRUSTDOWN                          0x00000020
#define IDH_THRUSTFORWARD                       0x00000021
#define IDH_THRUSTLEFT                          0x00000022
#define IDH_THRUSTREVERSE                       0x00000023
#define IDH_THRUSTRIGHT                         0x00000024
#define IDH_THRUSTUP                            0x00000025
#define IDH_UNLOAD_TYPES                        0x00000026
#define IDH_VIEWSECTOR                          0x00000027
#define IDH_VIEW_SYSTEM_KIT                     0x00000028
#define IDH_VOLUME_ADJUST                       0x00000029
#define IDH_YAW_LEFT                            0x0000002A
#define IDH_YAW_RIGHT                           0x0000002B

#endif      // _ADB 

#endif
