#ifndef IBLINKERS_H
#define IBLINKERS_H
//------------------------------------------------------------------------//
/*
	Header file generated by the HotKey editor (jy)
	Original data file: D:\win32\Conquest\Src\Hotkeys.utf

	$Header: /Conquest/App/Src/IBlinkers.h 3     6/28/99 3:31p Tmauer $
*/
//------------------------------------------------------------------------//
#ifndef IOBJECT_H
#include "IObject.h"
#endif

struct IBlinkers : IDAComponent
{
	//returns number of points
	virtual S32 GetBlinkers(Vector *points,SINGLE *intensity,S32 arraySize) = 0;
	virtual void Update(SINGLE dt) = 0;
};

struct BlinkersArchetype;

GENRESULT CreateBlinkers(COMPTR<IBlinkers> &ibs,struct BlinkersArchetype *bs_arch,INSTANCE_INDEX instanceIndex);
struct BlinkersArchetype *CreateBlinkersArchetype(const char *filename,ARCHETYPE_INDEX _parentIndex);
void DestroyBlinkersArchetype(BlinkersArchetype *bs_arch);

#endif