#ifndef MORPHMESH_H
#define MORPHMESH_H
//------------------------------------------------------------------------//
/*
	Header file generated by the HotKey editor (jy)
	Original data file: D:\win32\Conquest\Src\Hotkeys.utf

	$Header: /Conquest/App/Src/IMorphMesh.h 7     7/06/99 7:04p Rmarr $
*/
//------------------------------------------------------------------------//
#ifndef IOBJECT_H
#include "IObject.h"
#endif

#ifndef TSMARTPOINTER_H
#include <TSmartPointer.h>
#endif

#define MAX_TARGETS 6
#define MAX_CONTROL_POINTS 25


struct Parameters
{
	SINGLE scale;
};

struct IMorphMesh : IDAComponent
{
//	virtual void ReadINI (char *filename) = 0;

	virtual SINGLE GetMorphPos (Mesh **mesh0,Mesh **mesh1) = 0;
	virtual S32 GetVertices(Vector *vertices,Parameters *params) = 0;
	//virtual void GetParams(struct Parameters * params) = 0;
	virtual SINGLE GetMorphTime () = 0;
	virtual Mesh *GetMesh0() = 0;
	virtual void KillAnimQueue() = 0;
	virtual void MorphTo(S32 animID,SINGLE _transTime,bool _bLooping) = 0;
	virtual void QueueAnim(S32 animID,SINGLE _timeFromEnd,bool _bLooping) = 0;
	virtual void RunAnim(S32 animID,bool _bLooping) = 0;
	virtual void Update(SINGLE dt) = 0;

	//virtual void *GetBase() = 0;

};

struct MorphMeshArchetype;

GENRESULT CreateMorphMesh(COMPTR<IMorphMesh> &imm,struct MorphMeshArchetype *mm_arch);
struct MorphMeshArchetype *CreateMorphMeshArchetype(char *filename);
void DestroyMorphMeshArchetype(MorphMeshArchetype *mm_arch);

#endif