//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Globals.rc
//
#define IDS_APP_NAME                    1
#define IDS_VIEWMENU1                   2
#define IDDELETE                        3
#define IDS_VIEWCONFIRM                 3
#define IDS_VIEWPAUSE                   4
#define IDS_VIEWIGOPTIONS               5
#define IDS_VIEWTOOLBAR                 6
#define IDS_VIEWLOADSAVE                7
#define IDS_VIEWENDGAME                 8
#define IDS_VIEWMISSIONOBJECTIVES       9
#define IDS_VIEWMAINCAMERA              10
#define IDS_VIEWSECTOR                  11
#define IDS_BAD_REGISTRY_VALUE          12
#define IDS_3DOBJ_FILTER                13
#define IDS_WARRANTY_FILE               14
#define IDS_EULA_FILE                   15
#define IDS_VIEWENDMISSION              16
#define IDS_VIEWPLAYERMENU              17
#define IDS_VIEWOPTIONS                 18
#define IDS_VIEWSOUNDOPTIONS            19
#define IDS_VIEWSYSMAP                  20
#define IDS_VIEWCONQUESTOPTIONS         21
#define IDS_VIEWGRAPHICOPTIONS          22
#define IDS_VIEWMISSIONDATA             23
#define IDS_MISSION_FILTER              24
#define IDS_VIEWPROGRAMDATA             25
#define IDS_VIEWMESSAGEBOX              26
#define IDS_VIEWMOVIE                   27
#define IDS_VIEWBRIEFING                28
#define IDS_QUICK_MISSION_FILTER        29
#define IDS_VIEW_EFFECT_OPTIONS         30
#define IDS_VIEW_GLOBAL_DATA            31
#define IDS_OPEN3DB_FILTER              32
#define IDS_VIEWDIPLOMACYMENU           33
#define IDS_VIEWPLAYERCHATMENU          34
#define IDS_VIEWOBJECTIVEMENU           35
#define IDS_VIEWMAPSELECT               36
#define IDS_BUILD_VERSION               37
#define IDS_DYNAMIC_MISSION_FILTER      38
#define IDS_VIEWNEWPLAYER               39
#define IDS_PRODUCT_VERSION             40
#define IDS_LEGAL_MAINSCREEN            41
#define IDS_LEGAL_ABOUTBOX              42
#define IDS_VIEWCREDITS                 43
#define IDS_APP_NAMETM                  44
#define IDS_ALREADY_RUNNING             45
#define IDS_SPLASH_LOWRES               46
#define IDS_SPLASH_HIGHRES              47
#define IDS_VIEWLIGHTS                  83
#define IDS_VIEWMUSIC                   84
#define IDS_VIEWNEBULAE                 85
#define IDS_INSERTOBJECT                86
#define IDS_SELECTARCHETYPE             87
#define IDS_LOADINGOBJECT               88
#define IDS_INSERT3DOBJECT              90
#define IDS_VIEWCHAT                    91
#define IDS_VIEWFOG                     96
#define IDS_MENUPOS_FILE                98
#define IDS_MENUPOS_PREF                99
#define IDS_MENUPOS_VIEW                100
#define IDR_MENU1                       101
#define IDS_VIEW_GLOBALS                101
#define IDI_ICON1                       102
#define IDS_MENUPOS_MRU_MISSION         103
#define IDC_CURSOR_DEFAULT              104
#define IDS_EULA_TITLE                  104
#define IDC_CURSOR_LEFT                 105
#define IDS_EULA_ACCEPT                 105
#define IDC_CURSOR_RIGHT                106
#define IDS_EULA_DECLINE                106
#define IDC_CURSOR_UP                   107
#define IDC_CURSOR_DOWN                 108
#define IDC_CURSOR_UPRIGHT              109
#define IDC_CURSOR_UPLEFT               110
#define IDC_CURSOR_DOWNRIGHT            111
#define IDC_CURSOR_DOWNLEFT             112
#define IDC_CURSOR_PLACEOBJECT          113
#define IDC_CURSOR_SELLOBJECT           114
#define IDC_CURSOR_MOVEOBJECT           115
#define IDC_CURSOR_BAN                  116
#define IDC_CURSOR_MICRO_MOVE           117
#define IDC_CURSOR_MICRO_GOTO           118
#define IDC_CURSOR_POSTOOL              119
#define IDC_CURSOR_ATTACK               120
#define IDC_CURSOR_SPECIAL_ATTACK       121
#define IDC_CURSOR_HARVEST              122
#define IDC_CURSOR_RAM                  123
#define IDC_CURSOR_REPAIR               124
#define IDC_CURSOR_PATROL               125
#define IDC_CURSOR_JUMP                 126
#define IDC_CURSOR_BUILD                127
#define IDC_CURSOR_DEPLOY               128
#define IDC_CURSOR_GIVESHIP             129
#define IDC_CURSOR_ARROW                130
#define IDC_CURSOR_DEFEND               131
#define IDC_CURSOR_RESUPPLY             132
#define IDC_CURSOR_RALLY                133
#define IDC_CURSOR_MOVE_ADMIRAL         134
#define IDC_CURSOR_CAPTURE              135
#define IDD_DIALOG1                     140
#define IDD_DIALOG2                     141
#define IDD_DIALOG3                     142
#define IDD_DIALOG4                     143
#define IDD_DIALOG6                     145
#define IDR_DAHOTKEY1                   149
#define IDR_DAFONT_DEFAULT              150
#define IDR_SFX1                        151
#define IDD_FIELDLIST                   152
#define IDD_NAME                        153
#define IDD_DIALOG7                     154
#define IDR_PARSER1                     156
#define IDS_SCRIPT_FILTER               158
#define IDS_VIEW_MISSION                160
#define IDD_DIALOG8                     161
#define IDD_RUSE_NAME_DIALOG            164
#define IDD_RUSE_MULTILINK              165
#define IDR_RUSE_HOTKEY                 166
#define IDR_MENU2                       167
#define IDR_DAHOTKEY2                   169
#define IDS_MM_RESEARCH_MFRIGATE        170
#define IDS_COMPUTER_NAME               171
#define IDS_SELECT_BUILD_SLOT           172
#define IDS_SELECT_BUILD_SPACE          173
#define IDC_CURSOR_MICRO_RALLY          174
#define IDS_SELECT_BUILD_JUMPGATE       174
#define IDC_CURSOR_MIMIC                175
#define IDS_SLOT_AI_EASY                175
#define IDD_DIALOG5                     176
#define IDS_SLOT_AI_AVERAGE             176
#define IDD_DIALOG10                    177
#define IDS_SLOT_AI_HARD                177
#define IDD_CAMERA_LIST                 178
#define IDS_SLOT_AI_IMPOSIBLE           178
#define IDD_DIALOG11                    179
#define IDS_SLOT_AI_NIGHTMARE           179
#define IDD_DIALOG12                    180
#define IDC_CURSOR_INTERMEDIATE         183
#define IDD_DIALOG13                    184
#define IDC_CURSOR_FABREPAIR            185
#define IDD_DIALOG14                    186
#define IDC_CURSOR_WORM_ATTACK          188
#define IDC_CURSOR_MICRO_WORMHOLE       189
#define IDC_CURSOR_DEFAULT_BW           190
#define IDD_DIALOG9                     190
#define IDC_CURSOR_LEFT_BW              191
#define IDD_EULA_DIALOG                 191
#define IDC_CURSOR_RIGHT_BW             192
#define IDC_CURSOR_UP_BW                193
#define IDC_CURSOR_DOWN_BW              194
#define ID_EDITOR_MATERIALMANAGER       194
#define IDC_CURSOR_UPRIGHT_BW           195
#define IDC_CURSOR_UPLEFT_BW            196
#define IDC_CURSOR_DOWNRIGHT_BW         197
#define IDC_CURSOR_DOWNLEFT_BW          198
#define IDC_CURSOR_PLACEOBJECT_BW       199
#define IDC_CURSOR_SELLOBJECT_BW        200
#define IDC_CURSOR_MOVEOBJECT_BW        201
#define IDC_CURSOR_BAN_BW               202
#define IDC_CURSOR_MICRO_MOVE_BW        203
#define IDC_CURSOR_MICRO_GOTO_BW        204
#define IDC_CURSOR_POSTOOL_BW           205
#define IDC_CURSOR_ATTACK_BW            206
#define IDC_CURSOR_SPECIAL_ATTACK_BW    207
#define IDC_CURSOR_HARVEST_BW           208
#define IDC_CURSOR_RAM_BW               209
#define IDC_CURSOR_REPAIR_BW            210
#define IDC_CURSOR_PATROL_BW            211
#define IDC_CURSOR_JUMP_BW              212
#define IDC_CURSOR_BUILD_BW             213
#define IDC_CURSOR_DEPLOY_BW            214
#define IDC_CURSOR_ARROW_BW             215
#define IDC_CURSOR_DEFEND_BW            216
#define IDC_CURSOR_RESUPPLY_BW          217
#define IDC_CURSOR_RALLY_BW             218
#define IDC_CURSOR_MOVE_ADMIRAL_BW      219
#define IDC_CURSOR_CAPTURE_BW           220
#define IDC_CURSOR_MICRO_RALLY_BW       221
#define IDC_CURSOR_MIMIC_BW             222
#define IDC_CURSOR_INTERMEDIATE_BW      223
#define IDC_CURSOR_FABREPAIR_BW         224
#define IDC_CURSOR_WORM_ATTACK_BW       225
#define IDC_CURSOR_MICRO_WORMHOLE_BW    226
#define IDS_BEGIN_DISPLAY_NAMES         300
#define IDS_DOLLAR_SIGN                 301
#define IDS_MONEY_SEPARATOR             302
#define IDS_MT_HEADQUARTERS             303
#define IDS_MT_LIGHT_INDUSTRIAL         304
#define IDS_MT_HEAVY_INDUSTRIAL         305
#define IDS_MT_HITECH_INDUSTRIAL        306
#define IDS_MT_RESEARCH_FACILITY        307
#define IDS_MT_REFINERY                 308
#define IDS_MT_FORTRESS                 309
#define IDS_MT_CORVETTE                 310
#define IDS_MT_TANKER                   311
#define IDS_MT_LSAT                     312
#define IDS_MT_MISSILE_CRUISER          313
#define IDS_MT_FLEET_CARRIER            314
#define IDS_MT_BATTLESHIP               315
#define IDS_MT_SPACE_STATION            316
#define IDS_MT_DREADNOUGHT              317
#define IDS_MT_INFILTRATOR              318
#define IDS_MT_LANCER_CRUISER           319
#define IDS_MT_FABRICATOR               320
#define IDS_MT_DEBRIS                   321
#define IDS_MT_KHAMIR                   322
#define IDS_MT_SCOUT_CARRIER            323
#define IDS_MT_FRIGATE                  324
#define IDS_MT_MINELAYER                325
#define IDS_MT_HEAVY_CRUISER            326
#define IDS_MT_SUPER_CARRIER            327
#define IDS_MT_VORAAK_CANNON            328
#define IDS_MT_SCOUT                    329
#define IDS_MT_SEEKER                   329
#define IDS_MT_CRUISER                  330
#define IDS_MT_TEST                     331
#define IDS_MT_HIVE_CARRIER             331
#define IDS_MT_ZORAP_SUPPLY             332
#define IDS_MT_SIPHON_TANKER            333
#define IDS_MT_WEAVER                   334
#define IDS_MT_GREATER_WEAVER           335
#define IDS_MT_LEECH                    336
#define IDS_MT_BIOFORGE                 337
#define IDS_MT_BLAST_FURNACE            338
#define IDS_MT_CARPACE_PLANT            339
#define IDS_MT_CARRION_ROOST            340
#define IDS_MT_COCOON                   341
#define IDS_MT_EXPLOSIVES_RANGE         342
#define IDS_MT_EYE_STOCK                343
#define IDS_MT_FUSION_MILL              344
#define IDS_MT_MUTATION_COLONY          345
#define IDS_MT_NIAD                     346
#define IDS_MT_THRIPID                  347
#define IDS_MT_WARLORD_TRAINING         348
#define IDS_MT_DUAL_SPITTER             349
#define IDS_MT_PLASMA_SPITTER           350
#define IDS_MT_COLLECTOR                351
#define IDS_MT_PLANTATION               352
#define IDS_MT_BALLISTICS               353
#define IDS_MT_DISPLACEMENT             354
#define IDS_MT_PLASMA_HIVE              355
#define IDS_MT_HYBRIDCENTER             356
#define IDS_MT_ACROPOLIS                357
#define IDS_MT_OXIDATOR                 358
#define IDS_MT_PAVILION                 359
#define IDS_MT_SENTINELTOWER            360
#define IDS_MT_BUNKER                   361
#define IDS_MT_SANCTUM                  362
#define IDS_MT_EUTROMILL                363
#define IDS_MT_GREATERPAVILION          364
#define IDS_MT_HELIONVEIL               365
#define IDS_MT_CITADEL                  366
#define IDS_MT_XENOCHAMBER              367
#define IDS_MT_ANVIL                    368
#define IDS_MT_MUNITIONSANNEX           369
#define IDS_MT_TURBINEDOCK              370
#define IDS_MT_TALOREANMATRIX           371
#define IDS_MT_FORGER                   372
#define IDS_MT_STRATUM                  373
#define IDS_MT_GALIOT                   374
#define IDS_MT_TAOS                     375
#define IDS_MT_POLARIS                  376
#define IDS_MT_AURORA                   377
#define IDS_MT_ORACLE                   378
#define IDS_MT_ESPCOIL                  379
#define IDS_MT_STARBURST                380
#define IDS_MT_HYDROFOIL                381
#define IDS_MT_PROTEUS                  382
#define IDS_MT_LEGIONARE                383
#define IDS_MT_ATLAS                    384
#define IDS_MT_TRIREME                  385
#define IDS_MT_MONOLITH                 386
#define IDS_MT_HIGHCOUNSEL              387
#define IDS_MT_HANGER                   388
#define IDS_MT_JUMPGATE                 389
#define IDS_MT_PROPLAB                  390
#define IDS_MT_DISSECTION               391
#define IDS_MT_IONCANNON                392
#define IDS_MT_HEAVYREFINERY            393
#define IDS_MT_SUPERHEAVYREFINERY       394
#define IDS_MT_GREATERCOLLECTOR         395
#define IDS_MT_HALSEY                   396
#define IDS_MT_HAWKES                   397
#define IDS_MT_BENSON                   398
#define IDS_MT_SMIRNOFF                 399
#define IDS_TT_BEGIN_TOOLTIPS           400
#define IDS_MT_STEELE                   401
#define IDS_TT_HOMEWORLDRECT            402
#define IDS_TT_FLEETRECT                403
#define IDS_TT_LIGHTRECT                404
#define IDS_TT_REPAIRRECT               405
#define IDS_TT_HEAVYRECT                406
#define IDS_TT_NUCLEARRECT              407
#define IDS_TT_TECHINDRECT              407
#define IDS_TT_HANDSRECT                408
#define IDS_TT_ROTATELEFT               409
#define IDS_TT_ROTATERIGHT              410
#define IDS_TT_TECHRECT                 411
#define IDS_TT_RESEARCHRECT             411
#define IDS_TT_BUILD_TDREADNOUGHT       412
#define IDS_TT_BUILD_MFRIGATE           413
#define IDS_TT_BUILD_MHEAVY_CRUISER     414
#define IDS_TT_BUILD_MHIVE_CARRIER      415
#define IDS_TT_BUILD_MINFILTRATOR       416
#define IDS_TT_BUILD_MKHAMIR            417
#define IDS_TT_BUILD_MMOTHERSHIP        418
#define IDS_TT_BUILD_MSCOUT_CARRIER     419
#define IDS_TT_BUILD_MSENTINEL_CARRIER  420
#define IDS_TT_BUILD_MSPINELAYER        421
#define IDS_TT_BUILD_MINELAYER          421
#define IDS_TT_BUILD_MTANKER            422
#define IDS_TT_BUILD_MVORAAK_CANNON     423
#define IDS_TT_BUILD_TCORVETTE          424
#define IDS_TT_BUILD_TFLEET_CARRIER     425
#define IDS_TT_BUILD_TINFILTRATOR       426
#define IDS_TT_BUILD_TLANCER_CRUISER    427
#define IDS_TT_BUILD_TLASER_SATELLITE   428
#define IDS_TT_BUILD_TMIDAS_BATTLESHIP  429
#define IDS_TT_BUILD_TMISSILE_CRUISER   430
#define IDS_TT_BUILD_TRESEARCH_VESSEL   431
#define IDS_TT_BUILD_TTROOPSHIP         431
#define IDS_TT_BUILD_TSPACE_STATION     432
#define IDS_TT_BUILD_TTANKER            433
#define IDS_TT_BUILD_TTRANSPORT         434
#define IDS_TT_BUILD_ADVFAB             434
#define IDS_TT_BUILD_VBATTLESHIP        435
#define IDS_TT_BUILD_VCOBRA_BATTLESHIP  436
#define IDS_TT_BUILD_VDESTROYER         437
#define IDS_TT_BUILD_VFLAK_DEFENSE      438
#define IDS_TT_BUILD_VINFILTRATOR       439
#define IDS_TT_BUILD_VMONOLITH          440
#define IDS_TT_BUILD_VPROBE             441
#define IDS_TT_BUILD_VSIDEWINDER_CRUISER 442
#define IDS_TT_BUILD_SCLOAKING_CRUISER  443
#define IDS_TT_BUILD_SDESTROYER         444
#define IDS_TT_BUILD_SDRONECRUISER      445
#define IDS_TT_BUILD_SINFILTRATOR       446
#define IDS_TT_BUILD_SMINELAYER         447
#define IDS_TT_BUILD_SMISSILE_SYSTEM    448
#define IDS_TT_BUILD_SSCOUT             449
#define IDS_TT_BUILD_SSWARM_SATELLITE   450
#define IDS_TT_BUILD_STANKER            451
#define IDS_TT_BUILD_SWARCRUISER        452
#define IDS_TT_BUILD_VTANKER            453
#define IDS_TT_BUILD_TLIGHT_INDUSTRIAL  454
#define IDS_TT_BUILD_THEAVY_INDUSTRIAL  455
#define IDS_TT_BUILD_THIGH_TECH         456
#define IDS_TT_BUILD_TFORTRESS          457
#define IDS_TT_BUILD_TREFINERY          458
#define IDS_TT_BUILD_TRESEARCH          459
#define IDS_TT_BUILD_TFABRICATOR        460
#define IDS_TT_RESEARCH_TDREADNOUGHT    461
#define IDS_TT_RESEARCH_LASER_SATELLITE 462
#define IDS_TT_RESEARCH_MISSILE_CRUISER 463
#define IDS_TT_RESEARCH_MC_CLOAK        463
#define IDS_TT_RESEARCH_MIDAS_BATTLESHIP 464
#define IDS_TT_RESEARCH_SPACE_STATION   465
#define IDS_TT_RESEARCH_LANCER_CRUISER  466
#define IDS_TT_RESEARCH_KHAMIR          467
#define IDS_TT_RESEARCH_SPINELAYER      468
#define IDS_TT_RESEARCH_MINELAYER       468
#define IDS_TT_RESEARCH_HIVE_CARRIER    469
#define IDS_TT_RESEARCH_HEAVY_CRUISER   470
#define IDS_TT_RESEARCH_SENTINEL_CARRIER 471
#define IDS_TT_RESEARCH_VORAAK_CANNON   472
#define IDS_FLEET_ADD                   473
#define IDS_TT_FLEET_ADD                473
#define IDS_FLEET_SUBTRACT              474
#define IDS_TT_FLEET_REMOVE             474
#define IDS_FLEET_ATTACK                475
#define IDS_TT_FLEET_ATTACK             475
#define IDS_FLEET_DEFEND                476
#define IDS_TT_FLEET_DEFEND             476
#define IDS_TT_MINIMIZE_TOOLBAR         477
#define IDS_TT_RESTORE_TOOLBAR          478
#define IDS_TT_GAME_OPTIONS             479
#define IDS_TT_NEXT                     480
#define IDS_TT_PREVIOUS                 481
#define IDS_TT_FLEET_RAID               482
#define IDS_TT_BUILD_THEADQUARTERS      482
#define IDS_TT_STOP                     483
#define IDS_TT_PATROL                   484
#define IDS_TT_SALVAGE                  485
#define IDS_TT_RALLYPOINT               486
#define IDS_TT_REPAIR                   487
#define IDS_TT_SUPPLY                   488
#define IDS_TT_DIPLOMACY                489
#define IDS_TT_HEADQUARTERS             490
#define IDS_TT_RESEARCH                 491
#define IDS_TT_FLEET                    492
#define IDS_TT_LIGHTINDUSTRY            493
#define IDS_TT_INDUSTRY                 493
#define IDS_TT_HEAVYINDUSTRY            494
#define IDS_TT_TECHINDUSTRY             495
#define IDS_TT_TRANSFEROFFICER          496
#define IDS_TT_FLEETINVENTORY           497
#define IDS_TT_SPECIALWEAPON            498
#define IDS_TT_SELECTEDSHIP             499
#define IDS_TT_BACK                     500
#define IDS_TT_RESUPPLYUNIT             501
#define IDS_TT_RESUPPLYGROUP            502
#define IDS_TT_RESEARCHREQUIRED         503
#define IDS_TT_REFINERYREQUIRED         504
#define IDS_TT_RES_MC                   505
#define IDS_TT_RES_LSAT                 506
#define IDS_TT_RES_MCCLOAK              507
#define IDS_TT_RES_TROOPSHIP            508
#define IDS_TT_RES_TROOPSHIP1           508
#define IDS_TT_RES_ENGINE1              509
#define IDS_TT_RES_ENGINE2              510
#define IDS_TT_RES_ENGINE3              511
#define IDS_TT_RES_ENGINE4              512
#define IDS_TT_RES_BATTLESHIP           513
#define IDS_TT_RES_BATTLECHARGES        514
#define IDS_TT_RES_DREADNOUGHT          515
#define IDS_TT_RES_DREADSHIELD          516
#define IDS_TT_RES_FCPROBE              517
#define IDS_TT_RES_SPACESTATION         518
#define IDS_TT_RES_SUPPLYSHIP           519
#define IDS_TT_RES_HULL1                520
#define IDS_TT_RES_HULL2                521
#define IDS_TT_RES_HULL3                522
#define IDS_TT_RES_HULL4                523
#define IDS_TT_RES_WEAPON1              524
#define IDS_TT_RES_WEAPON2              525
#define IDS_TT_RES_WEAPON3              526
#define IDS_TT_RES_WEAPON4              527
#define IDS_TT_RES_LANCER               528
#define IDS_TT_RES_LANCERARC            529
#define IDS_TT_RES_SUPPLY1              530
#define IDS_TT_RES_SUPPLY2              531
#define IDS_TT_RES_SUPPLY3              532
#define IDS_TT_RES_SUPPLY4              533
#define IDS_TT_RES_SHIELD1              534
#define IDS_TT_RES_SHIELD2              535
#define IDS_TT_RES_SHIELD3              536
#define IDS_TT_RES_SHIELD4              537
#define IDS_TT_BUILD_TTENDER            538
#define IDS_TT_BUILD_TSUPPLY            538
#define IDS_TT_BUILD_TOUTPOST           539
#define IDS_TT_BUILD_TTURRET            540
#define IDS_TT_BUILD_TACADEMY           541
#define IDS_TT_BUILD_TPROPLAB           542
#define IDS_TT_RES_TENDER1              542
#define IDS_TT_BUILD_TADVHULL           543
#define IDS_TT_BUILD_TREPAIR            544
#define IDS_TT_BUILD_TSRSENSOR          545
#define IDS_TT_BUILD_TAWSLAB            546
#define IDS_TT_BUILD_TDEFENSEBAT        547
#define IDS_TT_BUILD_TMRSENSOR          548
#define IDS_TT_BUILD_TLOGISTICS         549
#define IDS_TT_BUILD_TNANOLAB           550
#define IDS_TT_BUILD_TFORCELAB          551
#define IDS_TT_BUILD_TLRSENSOR          552
#define IDS_TT_BUILD_TCDETECT           553
#define IDS_TT_GOTO                     554
#define IDS_METAL_SIGN                  555
#define IDS_GAS_SIGN                    556
#define IDS_CREW_SIGN                   557
#define IDS_TT_BUILD__TJUMPGATE         558
#define IDS_TT_BUILD_TSUPPLYSHIP        559
#define IDS_TT_BUILD_TFLEETOFFICER      560
#define IDS_TT_RES_THARVESTER1          561
#define IDS_TT_RES_THARVESTER2          562
#define IDS_TT_RES_TREPAIR              563
#define IDS_TT_RES_TMISSILE1            564
#define IDS_TT_RES_TMISSILE2            565
#define IDS_TT_RES_TFLEET1              566
#define IDS_TT_RES_TFLEET2              567
#define IDS_TT_RES_TFLEET3              568
#define IDS_TT_RES_TFLEET4              569
#define IDS_TT_RES_TSENSOR1             570
#define IDS_TT_RES_TSENSOR2             571
#define IDS_TT_RES_TSENSOR3             572
#define IDS_TT_RES_TSENSOR4             573
#define IDS_TT_RES_TFIGHTER1            574
#define IDS_TT_RES_TFIGHTER2            575
#define IDS_TT_RES_TFIGHTER3            576
#define IDS_TT_RES_TFIGHTER4            577
#define IDS_TT_RES_TSENSOR5             578
#define IDS_TT_ATTACK                   579
#define IDS_TT_DEFEND                   580
#define IDS_TT_STAND                    581
#define IDS_TT_IDLE                     582
#define IDS_TT_ESCORT                   583
#define IDS_TT_NONGUNBOAT               584
#define IDS_TT_CENTERVIEW               585
#define IDS_TT_STARMAP                  586
#define IDS_TT_CHAT                     587
#define IDS_TT_FORMFLEET                588
#define IDS_TT_DISBANDFLEET             589
#define IDS_TT_RESUPPLYFLEET            590
#define IDS_TT_REPAIRFLEET              591
#define IDS_TT_ASSAULT                  592
#define IDS_TT_TRANSFERADMIRAL          593
#define IDS_COMMAND_SIGN                594
#define IDS_TT_BALLISTICSLABREQUIRED    595
#define IDS_TT_OUTPOSTREQUIRED          596
#define IDS_TT_TENDERREQUIRED           597
#define IDS_TT_ADVHULLREQUIRED          598
#define IDS_TT_HANGERREQUIRED           599
#define IDS_TT_ACADEMYREQUIRED          600
#define IDS_TT_AWSLABREQUIRED           601
#define IDS_TT_HQREQUIRED               602
#define IDS_TT_HVYSHIPYARDREQUIRED      603
#define IDS_TT_PROPLABREQUIRED          604
#define IDS_TT_DISPLABREQUIRED          605
#define IDS_TT_BUILD_HANGER             606
#define IDS_TT_BUILD_JUMPGATE           607
#define IDS_TT_RES_TENDER2              608
#define IDS_TT_RES_TFIGHTER5            609
#define IDS_TT_RES_EXPLORAM1            610
#define IDS_TT_RES_EXPLORAM2            611
#define IDS_TT_RES_CAMO                 612
#define IDS_TT_RES_REPELLCLOUD          613
#define IDS_TT_RES_GRAVWELL             614
#define IDS_TT_RES_BOMBER               615
#define IDS_TT_RES_MUTATIONCOLONY       616
#define IDS_TT_RES_WARLORDTRAINING      617
#define IDS_TT_RES_EXPLOSIVESRANGE      618
#define IDS_TT_RES_NIAD                 619
#define IDS_TT_RES_FUSIONMILL           620
#define IDS_TT_RES_CARAPACEPLANT        621
#define IDS_TT_RES_HYBRIDCENTER         622
#define IDS_TT_RES_PLASMAHIVE           623
#define IDS_TT_RES_VORAAK               624
#define IDS_TT_RES_DISSECTION           625
#define IDS_TT_LIGHTSHIPYARDREQUIRED    626
#define IDS_TT_COCOONREQUIRED           627
#define IDS_TT_COLLECTORREQUIRED        628
#define IDS_TT_WARLORDREQUIRED          629
#define IDS_TT_THRIPIDREQUIRED          630
#define IDS_TT_NIADREQUIRED             631
#define IDS_TT_CARRIONROOSTREQUIRED     632
#define IDS_TT_MUTATIONCOLONYREQUIRED   633
#define IDS_TT_RES_HEAVYREFINERY        634
#define IDS_TT_RES_SUPERHEAVYREFINERY   635
#define IDS_TT_ACROPOLISREQUIRED        636
#define IDS_TT_OXIDATORREQUIRED         637
#define IDS_TT_PAVILIONREQUIRED         638
#define IDS_TT_BUNKERREQUIRED           639
#define IDS_TT_SENTINELTOWERREQUIRED    640
#define IDS_TT_GTRPAVILIONREQUIRED      641
#define IDS_TT_CITADELREQUIRED          642
#define IDS_TT_XENOCHAMBERREQUIRED      643
#define IDS_TT_MUNITANNEXREQUIRED       644
#define IDS_TT_RES_SYNTHESIS            645
#define IDS_TT_RES_COLLECTIVE           646
#define IDS_TT_RES_MASSDISRUPTOR        647
#define IDS_TT_RES_ECLIPSETORPEDO       648
#define IDS_TT_RES_DESTABILIZER         649
#define IDS_TT_RES_REPULSERBEAM         650
#define IDS_TT_PROTEUSREQUIRED          651
#define IDS_TT_TURBINEDOCKREQUIRED      652
#define IDS_PLANET_RATE                 653
#define IDS_PLANET_TYPE_HABITABLE       654
#define IDS_PLANET_TYPE_EARTH           654
#define IDS_PLANET_TYPE_METAL           655
#define IDS_PLANET_TYPE_MOON            655
#define IDS_PLANET_TYPE_GAS             656
#define IDS_PLANET_TYPE_OTHER           657
#define IDS_PLANET_TYPE_SWAMP           657
#define IDS_TT_RES_SIPHON1              658
#define IDS_TT_RES_SIPHON2              659
#define IDS_TT_RES_PLANTATION1          660
#define IDS_TT_RES_PLANTATION2          661
#define IDS_TT_RES_PLANTATION3          662
#define IDS_TT_RES_SIPHON3              663
#define IDS_TT_RES_ORE1                 664
#define IDS_TT_RES_ORE2                 665
#define IDS_TT_RES_ORE3                 666
#define IDS_TT_RES_GAS1                 667
#define IDS_TT_RES_GAS2                 668
#define IDS_TT_RES_GAS3                 669
#define IDS_MT_TAKAI                    670
#define IDS_MT_MORDELLA                 671
#define IDS_MT_AZKAR                    672
#define IDS_MT_VERLAK                   673
#define IDS_MT_KERTAK                   674
#define IDS_MT_ADTHRIPID                675
#define IDS_MT_MALKOR                   676
#define IDS_TT_RES_ENGINE5              677
#define IDS_TT_RES_TFLEET5              678
#define IDS_TT_RES_SUPPLY5              679
#define IDS_TT_RES_SHIELD5              680
#define IDS_TT_RES_WEAPON5              681
#define IDS_TT_RES_HULL5                682
#define IDS_TT_RES_GALIOT1              683
#define IDS_TT_RES_GALIOT2              684
#define IDS_TT_RES_EUTROMIL1            685
#define IDS_TT_RES_EUTROMIL2            686
#define IDS_MT_BLANUS                   687
#define IDS_MT_ELAN                     688
#define IDS_MT_VIVAC                    689
#define IDS_MT_JOULE                    690
#define IDS_MT_PROCYO                   691
#define IDS_MT_NATUS                    692
#define IDS_TT_BUILD_PORTAL             693
#define IDS_TT_RES_LEGIONAIRE1          694
#define IDS_TT_RES_LEGIONAIRE2          695
#define IDS_TT_RES_LEGIONAIRE3          696
#define IDS_TT_RES_LEGIONAIRE4          697
#define IDS_TT_MATRIX                   698
#define IDS_TT_PLANTREQUIRED            699
#define IDS_TT_GAME_MISSIONOBJ          700
#define IDS_TT_RES_AURORACLOAK          701
#define IDS_TT_RES_TRACTOR              702
#define IDS_TT_AUTOSUPP_ON              703
#define IDS_TT_AUTOSUPP_OFF             704
#define IDS_TT_AUTOSUPP_FULL            705
#define IDS_TT_GRCOLLECTORREQUIRED      706
#define IDS_TT_BLASTREQUIRED            707
#define IDS_TT_EYESTALKREQUIRED         708
#define IDS_TT_EXPLOREQUIRED            709
#define IDS_TT_DISSECTREQUIRED          710
#define IDS_TT_BIOFORGEREQUIRED         711
#define IDS_TT_FUSIONREQUIRED           712
#define IDS_TT_CARAPACEREQUIRED         713
#define IDS_TT_HYBRIDREQUIRED           714
#define IDS_TT_RES_GRCOLLECTOR          715
#define IDS_TT_AWSPROPREQUIRED          716
#define IDS_TT_ACADEMYDISPPROPREQUIRED  717
#define IDS_TT_SUPPLYREQUIRED           718
#define IDS_TT_SENSORREQUIRED           719
#define IDS_TT_COLLECTPLANTREQUIRED     720
#define IDS_TT_BIODISCARRREQUIRED       721
#define IDS_TT_EUTROOXIREQUIRED         722
#define IDS_TT_GRPAVHELREQUIRED         723
#define IDS_TT_MUNTURBREQUIRED          724
#define IDS_TT_MUNTURBXENOREQUIRED      725
#define IDS_TT_GRPAVPROTREQUIRED        726
#define IDS_TT_RES_TROOPSHIP2           727
#define IDS_TT_RES_TROOPSHIP3           728
#define IDS_TT_RES_LEECH1               729
#define IDS_TT_RES_LEECH2               730
#define IDS_MIMICKED_SHIP               731
#define IDS_JUMPGATE_NAME               732
#define IDS_TT_SPECIAL_CLOAK            733
#define IDS_TT_SPECIAL_TEMPEST          734
#define IDS_TT_SPECIAL_PROBE            735
#define IDS_TT_SPECIAL_VAMPIRE          736
#define IDS_TT_SPECIAL_AEGIS            737
#define IDS_TT_SPECIAL_PING             738
#define IDS_TT_SPECIAL_RAM              739
#define IDS_TT_SPECIAL_GRAVITYWELL      740
#define IDS_TT_SPECIAL_REPELLCLOUD      741
#define IDS_TT_SPECIAL_REPULSORBEAM     742
#define IDS_TT_SPECIAL_SYNTHESIS        743
#define IDS_TT_SPECIAL_CLOAKER          744
#define IDS_TT_SPECIAL_MASSDISRUPT      745
#define IDS_TT_SPECIAL_DESTABTORP       746
#define IDS_TT_SPECIAL_TRACTORBEAM      747
#define IDS_TT_SPECIAL_MIMIC            748
#define IDS_TT_SPECIAL_EXPLOMINES       749
#define IDS_MT_BLACKWELL                750
#define IDS_MT_ELITEDREADNOUGHT         751
#define IDS_MT_ELITEBATTLESHIP          752
#define IDS_MT_ELITEMONOLITH            753
#define IDS_MT_ELITETRIREME             754
#define IDS_MT_APOCARTHROPOD            755
#define IDS_TT_REPAIRREQUIRED           756
#define IDS_TT_LASERREQUIRED            757
#define IDS_TT_TERRANJUMPREQUIRED       758
#define IDS_TT_SPACEREQUIRED            759
#define IDS_TT_IONREQUIRED              760
#define IDS_TT_FABREQUIRED              761
#define IDS_TT_SUPSHIPREQUIRED          762
#define IDS_TT_HARVESTREQUIRED          763
#define IDS_TT_CORVETTEREQUIRED         764
#define IDS_TT_MISSILECRUISERREQUIRED   765
#define IDS_TT_INFILTRATORREQUIRED      766
#define IDS_TT_TROOPSHIPREQUIRED        767
#define IDS_TT_BATTLESHIPREQUIRED       768
#define IDS_TT_FLEETCARRIERREQUIRED     769
#define IDS_TT_LANCERCRUISERREQUIRED    770
#define IDS_TT_DREADNOUGHTREQUIRED      771
#define IDS_TT_MANTISJUMPREQUIRED       772
#define IDS_TT_PLASMASPITTERREQUIRED    773
#define IDS_TT_PLASMAHIVEREQUIRED       774
#define IDS_TT_VORAAKCANNONREQUIRED     775
#define IDS_TT_WEAVERREQUIRED           776
#define IDS_TT_ZORAPREQUIRED            777
#define IDS_TT_SIPHONREQUIRED           778
#define IDS_TT_SIPHONPREQUIRED          778
#define IDS_TT_SCOUTCARRIERREQUIRED     779
#define IDS_TT_FRIGATEREQUIRED          780
#define IDS_TT_KHAMIRREQUIRED           781
#define IDS_TT_HIVECARRIERREQUIRED      782
#define IDS_TT_SEEKERREQUIRED           783
#define IDS_TT_SCARABREQUIRED           784
#define IDS_TT_LEECHREQUIRED            785
#define IDS_TT_TIAMATREQUIRED           786
#define IDS_TT_SPINELAYERREQUIRED       787
#define IDS_TT_EUTROMILLREQUIRED        788
#define IDS_TT_CELJUMPGATEREQUIRED      789
#define IDS_TT_ANVILREQUIRED            790
#define IDS_TT_HELIONVEILREQUIRED       791
#define IDS_TT_ESPCOILREQUIRED          792
#define IDS_TT_HYDROFOILREQUIRED        793
#define IDS_TT_STARBURSTREQUIRED        794
#define IDS_TT_PORTALREQUIRED           795
#define IDS_TT_FORGERREQUIRED           796
#define IDS_TT_STRATUMREQUIRED          797
#define IDS_TT_GALIOTREQUIRED           798
#define IDS_TT_TAOSREQUIRED             799
#define IDS_TT_POLARISREQUIRED          800
#define IDS_TT_ORACLEREQUIRED           801
#define IDS_TT_LEGIONNAIREREQUIRED      802
#define IDS_TT_AURORAREQUIRED           803
#define IDS_TT_ATLASREQUIRED            804
#define IDS_TT_TRIREMEREQUIRED          805
#define IDS_TT_MONOLITHREQUIRED         806
#define IDS_TT_ORE                      807
#define IDS_TT_GAS                      808
#define IDS_TT_CREW                     809
#define IDS_TT_COMMANDPOINTS            810
#define IDS_MT_GREATER_PLANTATION       810
#define IDS_TT_INSUPPLY                 811
#define IDS_TT_OUTSUPPLY                812
#define IDS_TT_CP                       813
#define IDS_TT_PMISSILEPAK1             814
#define IDS_TT_RES_CMISSILE1            814
#define IDS_TT_PMISSILEPAK2             815
#define IDS_TT_RES_CMISSILE2            815
#define IDS_TT_DISABLED                 816
#define IDS_TT_HALSEYF1                 817
#define IDS_TT_HAWKESF2                 818
#define IDS_TT_TAKEIF3                  819
#define IDS_TT_STEELEF4                 820
#define IDS_TT_SMIRNOFFF5               821
#define IDS_TT_BENSONF6                 822
#define IDS_TT_MORDELLAF1               823
#define IDS_TT_AZKARF2                  824
#define IDS_TT_VERLAKF3                 825
#define IDS_TT_KERTAKF4                 826
#define IDS_TT_THRIPIDF5                827
#define IDS_TT_MALKORF6                 828
#define IDS_TT_BLANUSF1                 829
#define IDS_TT_ELANF2                   830
#define IDS_TT_VIVACF3                  831
#define IDS_TT_JOULEF4                  832
#define IDS_TT_PROCYOF5                 833
#define IDS_TT_NATUSF6                  834
#define IDS_TT_SPECIAL_CLOAK2           835
#define IDS_TT_SPECIAL_TEMPEST2         836
#define IDS_TT_SPECIAL_PROBE2           837
#define IDS_TT_SPECIAL_VAMPIRE2         838
#define IDS_TT_SPECIAL_AEGIS2           839
#define IDS_TT_SPECIAL_PING2            840
#define IDS_TT_SPECIAL_RAM2             841
#define IDS_TT_SPECIAL_GRAVITYWELL2     842
#define IDS_TT_SPECIAL_REPELLCLOUD2     843
#define IDS_TT_SPECIAL_REPULSORBEAM2    844
#define IDS_TT_SPECIAL_SYNTHESIS2       845
#define IDS_TT_SPECIAL_CLOAKER2         846
#define IDS_TT_SPECIAL_MASSDISRUPT2     847
#define IDS_TT_SPECIAL_DESTABTORP2      848
#define IDS_TT_SPECIAL_TRACTORBEAM2     849
#define IDS_TT_SPECIAL_MIMIC2           850
#define IDS_TT_SPECIAL_EXPLOMINES2      851
#define IDS_TT_SPECIAL_PULSEMINES       852
#define IDS_TT_SPECIAL_PULSEMINES2      853
#define IDS_TT_FIGHTER_STANCE_NORMAL    854
#define IDS_TT_FIGHTER_STANCE_PATROL    855
#define IDS_TT_ADMIRAL_T_PEACE          856
#define IDS_TT_ADMIRAL_T_HOLD           857
#define IDS_TT_ADMIRAL_T_DEFEND         858
#define IDS_TT_ADMIRAL_T_SEEK           859
#define IDS_BEGIN_FONTS                 900
#define IDS_STATUSBAR_FONT              901
#define IDS_DEFAULTLISTBOX_FONT         902
#define IDS_HINTBOX_FONT                903
#define IDS_TOOLTIP_FONT                904
#define IDS_TOOLBAR_BUILD_FONT          905
#define IDS_TOOLBAR_MONEY_FONT          906
#define IDS_BUTTON_FONT                 907
#define IDS_TELETYPE_FONT               908
#define IDS_DESCRIPTION_FONT            909
#define IDS_STATIC_CONTROL_FONT         910
#define IDS_GAMEROOMLIST_FONT           911
#define IDS_CHATLIST_FONT               912
#define IDS_LOCAL_DISPLAYNAME_FONT      913
#define IDS_SMALL_DROPDOWN_FONT         914
#define IDS_CONTEXTWINDOW               915
#define IDS_ENDGAMEBANNER_FONT          916
#define IDS_SCOREBOARD_FONT             917
#define IDS_MESSAGEBOX_FONT             918
#define IDS_OPENING_FONT                919
#define IDS_FUTURELB_FONT               920
#define IDS_FONT_PLAYERS                921
#define IDS_PLANET_TITLE_FONT           922
#define IDS_FONT_DROPSMALL              923
#define IDS_FONT_OCR_16_700             924
#define IDS_NEURO_14_600                925
#define IDS_COURIER_12_400              926
#define IDS_NEURO_12_400                927
#define IDS_PLANET_INFO_FONT            928
#define IDS_FONT_OBJECTIVES             929
#define IDS_FONT_COUNTDOWN              930
#define IDS_SCOREBOARD_BOLD_FONT        931
#define IDS_BUTTON3D_FONT               932
#define IDS_SUBTITLE_FONT               933
#define IDS_BEGIN_STATUS                1000
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_LIST1                       1002
#define IDC_EDIT3                       1002
#define IDS_OUTOFBOUNDS                 1003
#define IDC_LIST2                       1003
#define IDC_CL_LIST                     1003
#define IDS_SYSMAPMOVE                  1004
#define IDM_JOIN_GAME                   1004
#define IDS_SYSMAPGOTO                  1005
#define IDM_CREATE_GAME                 1005
#define IDC_SPIN1                       1005
#define IDS_MOVEOBJECT                  1006
#define IDC_CHECK1                      1006
#define IDC_SPIN2                       1006
#define IDS_ATTACKOBJECT                1007
#define IDC_SLIDER1                     1007
#define IDC_SPIN3                       1007
#define IDC_SLIDER2                     1008
#define IDM_ADD_PART                    1008
#define IDS_OFFLIMITS                   1008
#define IDC_CHECK2                      1009
#define IDC_PART_NAME                   1009
#define IDS_SELLOBJECT                  1009
#define IDS_MISSION_LOADING             1010
#define IDC_SLIDER3                     1010
#define IDC_RICHEDIT1                   1010
#define IDS_HARVESTOBJECT               1011
#define IDC_CHECK3                      1011
#define IDC_BUTTON1                     1011
#define IDS_FABREPAIR                   1012
#define IDC_SLIDER4                     1012
#define IDC_BUTTON2                     1012
#define IDS_RAMOBJECT                   1013
#define IDC_CHECK4                      1013
#define IDC_RUSE_EDIT_NAME              1014
#define IDS_PATROLOBJECT                1014
#define IDC_RUSE_EDIT1                  1015
#define IDS_PATROL_MAX                  1015
#define IDC_RUSE_ISVISIBLE              1016
#define IDS_JUMPOBJECT                  1016
#define IDS_DEPLOYOBJECT                1017
#define IDS_SPECIALATTACKOBJECT         1019
#define IDC_RUSE_DELETE                 1020
#define IDS_JUMPCAMERA                  1020
#define IDC_RUSE_ISLOCKED               1021
#define IDS_UNKJUMPCAMERA               1021
#define IDC_CL_NEW                      1021
#define IDS_JUMPBOTH                    1022
#define IDC_CL_DELETE                   1022
#define IDC_TREE1                       1022
#define IDS_ESCORTOBJECT                1023
#define IDC_CL_COPY                     1023
#define IDC_STATIC_VERSION              1023
#define IDS_RESUPPLYOBJECT              1024
#define IDC_CL_SETLOOK                  1024
#define IDDEBUG                         1024
#define IDS_DEFENDAREA                  1025
#define IDC_CL_SETPOS                   1025
#define IDC_PICTURE1                    1025
#define IDC_CL_VIEW                     1026
#define IDS_SYSMAPMOVE_R                1026
#define IDC_EULA_TEXT                   1026
#define IDC_CL_LOOKFROM                 1027
#define IDS_SYSMAPGOTO_R                1027
#define IDS_ENTERSHIPNAME               1028
#define IDC_CL_GOTO                     1028
#define IDS_BUILDFULL                   1030
#define IDS_HARVESTUNLOAD               1031
#define IDS_HARVESTSTART                1032
#define IDS_SETRALLYPOINT               1033
#define IDS_ATTACH_ADMIRAL              1034
#define IDS_DETACH_ADMIRAL              1035
#define IDS_RESUPPLYDENIED              1036
#define IDS_ATTACKOUTOFRANGE            1037
#define IDS_RESUPPLYDENIED2             1038
#define IDS_SHIPREPAIR                  1039
#define IDS_SUPPLYESCORT                1040
#define IDS_SUPPLYAREA                  1041
#define IDS_SPECIALDENIED               1042
#define IDS_RESUPPLYDENIED3             1043
#define IDS_ATTACH_ADMIRAL_FULL         1044
#define IDS_CAPTUREOBJECT               1045
#define IDS_BAN_HARDFOG                 1046
#define IDS_HBSTATUS_DEFAULT            1047
#define IDS_SYSMAPMOVEONLY              1048
#define IDS_SHIP_RESUPPLY               1049
#define IDS_SYSMAPRALLY                 1050
#define IDS_SYSMAPRALLYONLY             1051
#define IDS_HBSTATUS_RALLYPOINT         1052
#define IDS_HBSTATUS_STOP               1053
#define IDS_HBSTATUS_SALVAGE            1054
#define IDS_ENTERCHATTEXT               1055
#define IDS_MIMIC                       1056
#define IDS_JUMPFORBIDDEN               1057
#define IDS_SELECT_MISSION              1058
#define IDS_MOVEOBJECT_R                1059
#define IDS_ATTACKOBJECT_R              1060
#define IDS_SHIP_REPAIR_AND_RESUPPLY_R  1061
#define IDS_SHIPREPAIR_R                1062
#define IDS_CAPTUREOBJECT_R             1063
#define IDS_SHIPSELL_R                  1064
#define IDS_ATTACH_FIND                 1065
#define IDS_HARVESTOBJECT_R             1066
#define IDS_JUMPOBJECT_R                1072
#define IDS_JUMPBOTH_R                  1073
#define IDS_JUMPFULL_R                  1074
#define IDS_JUMPCAMERA_R                1075
#define IDS_HARVESTSTART_R              1076
#define IDS_HARVESTUNLOAD_R             1077
#define IDS_SYSMAPMOVEONLY_R            1078
#define IDS_RESUPPLYOBJECT_R            1081
#define IDS_WORMHOLE_GENERATOR_R        1082
#define IDS_SECTORMAPGOTO               1085
#define IDS_SECTORMAPGOTO_R             1086
#define IDS_PATROL                      1087
#define IDS_PATROL_R                    1088
#define IDS_WORMHOLE_GENERATOR          1088
#define IDS_SELECT_SPECIAL_ABILITY      1089
#define IDS_CAPTUREDENIED               1090
#define IDS_SHIPSELL                    1091
#define IDS_SYNTHESIS                   1092
#define IDS_INTERMEDIATE_DOCK           1093
#define IDS_SHIP_REPAIR_AND_RESUPPLY    1096
#define IDS_BEGIN_BUTTON_TEXT           1100
#define IDS_TEST_BUTTON_TEXT            1101
#define IDS_SINGLE_PLAYER               1102
#define IDS_MULTI_PLAYER                1103
#define IDS_OPTIONS                     1104
#define IDS_BACK                        1105
#define IDS_INTRODUCTION                1106
#define IDS_SKIRMISH                    1107
#define IDS_JOIN                        1108
#define IDS_CREATE                      1109
#define IDS_DEFAULT_IP_ADDRESS          1110
#define IDS_NEXT                        1111
#define IDS_QUIT                        1112
#define IDS_CANCEL                      1113
#define IDS_APPLY                       1114
#define IDS_YES                         1115
#define IDS_NO                          1116
#define IDS_RESUME                      1117
#define IDS_MPLAYER_SETTINGS            1118
#define IDS_OPEN                        1119
#define IDS_MPLAYER_FINAL               1120
#define IDS_ACCEPT                      1121
#define IDS_START                       1122
#define IDS_SAVE                        1123
#define IDS_OK                          1124
#define IDS_CONTINUE                    1125
#define IDS_LOAD                        1126
#define IDS_CREDITS                     1127
#define IDS_MISSION_OBJECTIVES          1128
#define IDS_END_MISSION                 1129
#define IDS_RESTART                     1130
#define IDS_RESIGN                      1131
#define IDS_RETURN_TO_GAME              1132
#define IDS_GAME                        1133
#define IDS_SOUND                       1134
#define IDS_GRAPHICS                    1135
#define IDS_ON                          1136
#define IDS_OFF                         1137
#define IDS_NEW_PLAYER                  1138
#define IDS_DELETE_PLAYER               1139
#define IDS_LOAD_SAVED_GAME             1140
#define IDS_LOAD_CUSTOM                 1141
#define IDS_BUTTON_TERRAN               1142
#define IDS_BUTTON_MANTIS               1143
#define IDS_NEW_CAMPAIGN                1144
#define IDS_REPLAY                      1145
#define IDS_REPAIR_FLEET                1146
#define IDS_RESUPPLY_FLEET              1147
#define IDS_DISBAND_FLEET               1148
#define IDS_CREATE_FLEET                1149
#define IDS_TRANSFER_FLAGSHIP           1150
#define IDS_RESET                       1151
#define IDS_CLOSE                       1152
#define IDS_ENEMIES                     1153
#define IDS_ALLIES                      1154
#define IDS_EVERYONE                    1155
#define IDS_CHANGE_NAME                 1156
#define IDS_TERRAN_CAMPAIGN             1157
#define IDS_MANTIS_TRAINING             1158
#define IDS_SOLARIAN_TRAINING           1159
#define IDS_LOAD_QUICKBATTLE            1160
#define IDS_HOST_SAVEDGAME              1161
#define IDS_ABDICATE                    1162
#define IDS_BRIEFING                    1165
#define IDS_BUTTON_MAPTYPE              1166
#define IDS_BEGIN_HELP_BOX_TEXT         1300
#define IDS_HELP_INTERNET               1301
#define IDS_HELP_NETWORK                1302
#define IDS_HELP_MODEM                  1303
#define IDS_HELP_SERIAL                 1304
#define IDS_HELP_NETCONNECT             1305
#define IDS_HELP_CHOOSE_CREATE          1306
#define IDS_HELP_IPADDRESS              1307
#define IDS_HELP_CHOOSE_JOIN            1308
#define IDS_HELP_NO_DEFAULT_GAMES       1309
#define IDS_HELP_SEARCHING_FOR_GAMES    1310
#define IDS_HELP_CREATE_LAN             1311
#define IDS_HELP_NO_LAN_GAMES           1312
#define IDS_HELP_CREATEFAILED           1313
#define IDS_HELP_JOINFAILED             1314
#define IDS_HELP_TCP_LAN                1315
#define IDS_HELP_ZONE                   1316
#define IDS_HELP_NODISCSPACE            1317
#define IDS_HELP_DIR_MISSING            1318
#define IDS_HELP_ZONEPENDING            1319
#define IDS_HELP_LAUNCHFAILED           1320
#define IDS_HELP_SELECTGAME             1321
#define IDS_HELP_SELECTGAMENOW          1322
#define IDS_HELP_PRESSSTART             1323
#define IDS_HELP_WAITSTART              1324
#define IDS_HELP_SIGNALREADY            1325
#define IDS_HELP_UNK_PROVIDER           1326
#define IDS_HELP_HOSTBUSY               1327
#define IDS_HELP_BOOTED                 1328
#define IDS_HELP_WARNBOOT               1329
#define IDS_HELP_HOSTWAITSTART          1330
#define IDS_HELP_DUPLICATENAME          1331
#define IDS_HELP_SOLOGAME               1332
#define IDS_HELP_BADVERSION             1333
#define IDS_HELP_CLIENTWAITDATA         1334
#define IDS_HELP_LOBBYFAILED            1335
#define IDS_HELP_NOSOUND                1336
#define IDS_HELP_NOCAPTURE              1337
#define IDS_HELP_WARNDROP               1338
#define IDS_HELP_WARNLOBBYDELAY         1339
#define IDS_HELP_GOBACK                 1340
#define IDS_TELETYPE_ALERT              1341
#define IDS_HELP_LOADFAILED             1342
#define IDS_HELP_PLAYERDROPPED          1343
#define IDS_HELP_REMOTELOADFAILED       1344
#define IDS_CONFIRM                     1345
#define IDS_PLAYER_EXISTS               1346
#define IDS_ERROR                       1347
#define IDS_ASK_DELETE                  1348
#define IDS_HELP_CREATE_INTERNET        1349
#define IDS_HELP_CREATE_DEFAULT         1350
#define IDS_HELP_CREATE_SERIAL          1351
#define IDS_HELP_CREATE_MODEM           1352
#define IDS_HELP_JOIN_LAN               1353
#define IDS_HELP_JOIN_INTERNET          1354
#define IDS_HELP_JOIN_DEFAULT           1355
#define IDS_HELP_JOIN_MODEM             1356
#define IDS_HELP_JOIN_SERIAL            1357
#define IDS_OVERWRITE_QUERY             1358
#define IDS_HELP_ENTER_NAME             1359
#define IDS_HELP_NAME_ERROR             1360
#define IDS_HELP_CREATENOW              1361
#define IDS_CREATE_LAN_GAME             1362
#define IDS_HELP_SOLOHUMAN              1363
#define IDS_HELP_REPEATCOMPUTER         1364
#define IDS_HELP_ONETEAM                1365
#define IDS_HELP_DELETE                 1366
#define IDS_HELP_CONNFAILED             1367
#define IDS_HELP_COOPCHECK              1368
#define IDS_HELP_ALLCOOP                1369
#define IDS_HELP_NOGAMES                1370
#define IDS_WARN_CHEATING               1371
#define IDS_NETWORK_ERROR               1372
#define IDS_WARN_NETWORK_DIFFICULTY     1373
#define IDS_HELP_NO3DCARD               1374
#define IDS_MEDIA_FAILED                1375
#define IDS_REINSERT_CDROM              1376
#define IDS_HELP_COOPTEAM               1377
#define IDS_HELP_NORESIGN               1378
#define IDS_HELP_TOO_HIRES              1379
#define IDS_HELP_BAD_HARDWARE           1380
#define IDS_HELP_DEFAULT_TO_SOFTWARE    1381
#define IDS_HELP_NOHUMANS               1382
#define IDS_HELP_NOSWAP                 1383
#define IDS_HELP_OUTOFMEMORY            1384
#define IDS_HELP_COOPCOMPUTER           1385
#define IDS_HELP_TOOMANYPLAYERS         1386
#define IDS_HELP_WEB                    1387
#define IDS_BEGIN_STATIC_TEXT           1400
#define IDS_ENTER_PLAYER_NAME           1401
#define IDS_ENTER_IP_ADDRESS            1402
#define IDS_VOLUME_CONTROL              1403
#define IDS_ENTER_SESSION_NAME          1404
#define IDS_STATIC_SHUTDOWNWAIT         1405
#define IDS_CONFIRM_QUIT                1406
#define IDS_TITLE_SELECTGAME            1407
#define IDS_STATIC_PLAYER               1408
#define IDS_STATIC_SESSION              1409
#define IDS_ENTER_RACE                  1410
#define IDS_ENTER_COLOR                 1411
#define IDS_ENTER_TEAM                  1412
#define IDS_STATIC_MAP                  1413
#define IDS_SELECTED_MAP                1414
#define IDS_STATIC_CHATBOX              1415
#define IDS_GAMEPAUSED                  1416
#define IDS_IGOPTIONS_TITLE             1417
#define IDS_STATIC_OPTIONS              1418
#define IDS_STATIC_GAMETYPE             1419
#define IDS_STATIC_GAMESPEED            1420
#define IDS_STATIC_ARTIFACTS            1421
#define IDS_STATIC_MONEY                1422
#define IDS_STATIC_RESEARCH             1423
#define IDS_STATIC_MAPTYPE              1424
#define IDS_STATIC_MAPSIZE              1425
#define IDS_STATIC_TERRAIN              1426
#define IDS_STATIC_RESOURCES            1427
#define IDS_STATIC_VERSION              1428
#define IDS_PLAYER_ENTERING             1429
#define IDS_PLAYER_EXITING              1430
#define IDS_STATIC_LOADGAME             1431
#define IDS_STATIC_SAVEGAME             1432
#define IDS_STATIC_FILENAME             1433
#define IDS_FLEET_SIZE                  1434
#define IDS_SKILL                       1435
#define IDS_FLEET_SKILL                 1435
#define IDS_BONUS                       1436
#define IDS_FLEET_BONUS                 1436
#define IDS_STATIC_SYSTEMS              1437
#define IDS_HELP_WAITINGTOCONNECT       1438
#define IDS_XFERPROGRESS                1439
#define IDS_IND_SHIPCLASS               1440
#define IDS_IND_HULL                    1441
#define IDS_IND_SUPPLIES                1442
#define IDS_IND_ARMOR                   1443
#define IDS_IND_ARMOR_UP                1443
#define IDS_IND_ENGINES                 1444
#define IDS_IND_ENGINES_UP              1444
#define IDS_IND_WEAPONS                 1445
#define IDS_IND_WEAPONS_UP              1445
#define IDS_IND_SHIELDS                 1446
#define IDS_IND_SHIELDS_UP              1446
#define IDS_IND_KILLS                   1447
#define IDS_PLAYER_PAUSED               1448
#define IDS_STATIC_UNITS                1449
#define IDS_REQUEST_CHAT                1450
#define IDS_STATIC_MAPFILE              1451
#define IDS_SCOREBOARD                  1452
#define IDS_SCORE                       1453
#define IDS_MUSIC                       1454
#define IDS_EFFECTS                     1455
#define IDS_COMMS                       1456
#define IDS_NETCHAT                     1457
#define IDS_TOOLTIPS                    1458
#define IDS_STATUSTEXT                  1459
#define IDS_FOG                         1460
#define IDS_MAPROTATE                   1461
#define IDS_ROLLOVER                    1462
#define IDS_CURSOR_SENSITIVITY          1463
#define IDS_GRAPHICS_MENU               1464
#define IDS_HARDWARE_DEVICES            1464
#define IDS_GAMMA                       1465
#define IDS_WEAPON_TRAILS               1466
#define IDS_EMMISIVE_TEXTURES           1467
#define IDS_LOD                         1468
#define IDS_USE_TEXTURES                1469
#define IDS_DRAW_BACKGROUND             1470
#define IDS_RESOURCES                   1471
#define IDS_ENTER_NAME                  1472
#define IDS_SELECT_CAMPAIGN             1473
#define IDS_STATIC_SKIRMISH             1474
#define IDS_STATIC_INTRO                1475
#define IDS_RIGHTCLICK                  1476
#define IDS_IND_SENSOR_UP               1477
#define IDS_IND_SUPPLY_UP               1478
#define IDS_IND_TROOPSHIP_UP            1479
#define IDS_IND_HARVESTER_UP            1480
#define IDS_IND_TENDER_UP               1481
#define IDS_IND_FIGHTER_UP              1482
#define IDS_IND_FLEET_UP                1483
#define IDS_IND_MISSILEPAK_UP           1484
#define IDS_IND_RAM_UP                  1485
#define IDS_IND_METAL                   1486
#define IDS_IND_GAS                     1487
#define IDS_SCROLL_RATE                 1488
#define IDS_NET_CONNECT                 1489
#define IDS_LOAD_DESCRIPTION            1490
#define IDS_SAVE_DESCRIPTION            1491
#define IDS_HARDWARE                    1492
#define IDS_RESOLUTION                  1493
#define IDS_ENTER_STATE                 1494
#define IDS_PLAYER_LIST                 1495
#define IDS_PING                        1496
#define IDS_STATIC_HELP                 1497
#define IDS_STATIC_GAME                 1498
#define IDS_SPEED                       1499
#define IDS_MORE_STATICS                1500
#define IDS_YOU_WIN                     1501
#define IDS_YOU_LOSE                    1502
#define IDS_FORMAT_GAMETIME             1503
#define IDS_STATIC_VISIBILITY           1504
#define IDS_DEVICE_CHOICE               1505
#define IDS_SOFTWARE                    1506
#define IDS_METAL_STORE                 1507
#define IDS_GAS_STORE                   1508
#define IDS_CREW_STORE                  1509
#define IDS_STATIC_RANDOMMAPS           1510
#define IDS_STATIC_SUPPLIEDMAPS         1511
#define IDS_STATIC_SAVEDMAPS            1512
#define IDS_STATIC_HARDWARE_CURSOR      1513
#define IDS_STATIC_PRODUCTID            1514
#define IDS_STATIC_SPECTATORS           1515
#define IDS_STATIC_LOCKDIPLOMACY        1516
#define IDS_STATIC_REGENERATE           1517
#define IDS_STATIC_LOCKSETTINGS         1518
#define IDS_FORMAT_TIMETOBOOT           1519
#define IDS_PLAYER_CONGESTED            1520
#define IDS_STATIC_DIFFICULTY           1521
#define IDS_STATIC_ORE                  1522
#define IDS_STATIC_GAS                  1523
#define IDS_STATIC_CREW                 1524
#define IDS_STATIC_ALLIED               1525
#define IDS_STATIC_DIPLOMACY            1526
#define IDS_STATIC_NEWPLAYER            1527
#define IDS_TITLE_UNITS                 1528
#define IDS_TITLE_BUILDINGS             1529
#define IDS_TITLE_TERRITORY             1530
#define IDS_TITLE_RESOURCES             1531
#define IDS_TITLE_TOTAL                 1532
#define IDS_TITLE_MADE                  1533
#define IDS_TITLE_LOST                  1534
#define IDS_TITLE_KILLS                 1535
#define IDS_TITLE_CONVERTED             1536
#define IDS_TITLE_ADMIRALS              1537
#define IDS_TITLE_DESTROYED             1538
#define IDS_TITLE_RESEARCH              1539
#define IDS_TITLE_CREW                  1540
#define IDS_TITLE_ORE                   1541
#define IDS_TITLE_GAS                   1542
#define IDS_TITLE_JUMPGATES             1543
#define IDS_TITLE_PLANETS               1544
#define IDS_TITLE_EXPLOREDSYSTEMS       1545
#define IDS_LOAD_MISSION                1546
#define IDS_CONTEXT_LOCATION            1547
#define IDS_HYPERSPACE_LOC              1548
#define IDS_IND_LEECH_UP                1549
#define IDS_IND_LEGIONAIRE_UP           1550
#define IDS_IND_SIPHON_UP               1551
#define IDS_IND_GALIOT_UP               1552
#define IDS_TERRAIN                     1553
#define IDS_STATIC_IPADDRESS            1554
#define IDS_STATIC_CHAT                 1555
#define IDS_FORMAT_HOSTPAUSED           1556
#define IDS_STATIC_EASY                 1557
#define IDS_STATIC_MEDIUM               1558
#define IDS_STATIC_HARD                 1559
#define IDS_SHIPS_3D                    1560
#define IDS_STATIC_CMDPOINTS            1561
#define IDS_REQUEST_TEAM_CHAT           1562
#define IDS_SUBTITLE                    1563
#define IDS_BEGIN_LIST_TEXT             1600
#define IDS_NETWORKGAME                 1601
#define IDS_INTERNETGAME                1602
#define IDS_MODEMGAME                   1603
#define IDS_SERIALGAME                  1604
#define IDS_ZONEGAME                    1605
#define IDS_RACESELECT_HUMAN            1606
#define IDS_RACESELECT_MANTIS           1607
#define IDS_COLORSELECT_YELLOW          1608
#define IDS_COLORSELECT_RED             1609
#define IDS_COLORSELECT_WHITE           1610
#define IDS_COLORSELECT_BLUE            1611
#define IDS_COLORSELECT_GREEN           1612
#define IDS_COLORSELECT_BROWN           1613
#define IDS_COLORSELECT_PURPLE          1614
#define IDS_COLORSELECT_AQUA            1615
#define IDS_TEAMSELECT_1                1616
#define IDS_TEAMSELECT_2                1617
#define IDS_TEAMSELECT_3                1618
#define IDS_TEAMSELECT_4                1619
#define IDS_TEAMSELECT_NONE             1620
#define IDS_GAMETYPE_KILL_UNITS         1621
#define IDS_GAMETYPE_KILL_ALL_PLATS     1622
#define IDS_GAMETYPE_KILL_PLATFAB       1622
#define IDS_GAMETYPE_KILL_BUILD_PLATS   1623
#define IDS_WEB_BUTTON                  1623
#define IDS_GAMETYPE_KILL_HQ_PLATS      1624
#define IDS_GAMESPEED_SLOW              1625
#define IDS_GAMESPEED_NORMAL            1626
#define IDS_GAMESPEED_FAST              1627
#define IDS_ARTIFACTS_ON                1628
#define IDS_ARTIFACTS_OFF               1629
#define IDS_MONEY_LOW                   1630
#define IDS_MONEY_MEDIUM                1631
#define IDS_MONEY_HIGH                  1632
#define IDS_RESEARCH_NONE               1633
#define IDS_RESEARCH_FULL               1634
#define IDS_MAPTYPE_RANDOM              1635
#define IDS_MAPTYPE_FILE                1636
#define IDS_MAPTYPE_MULTIPLAYER         1636
#define IDS_MAPSIZE_SMALL               1637
#define IDS_MAPSIZE_MEDIUM              1638
#define IDS_MAPSIZE_LARGE               1639
#define IDS_TERRAIN_LIGHT               1640
#define IDS_TERRAIN_MEDIUM              1641
#define IDS_TERRAIN_HEAVY               1642
#define IDS_RESOURCES_SCARCE            1643
#define IDS_RESOURCES_NORMAL            1644
#define IDS_RESOURCES_PLENTIFUL         1645
#define IDS_SLOT_OPEN                   1646
#define IDS_SLOT_CLOSED                 1647
#define IDS_SLOT_COMPUTER               1648
#define IDS_SLOT_READY                  1649
#define IDS_SLOT_ACTIVE                 1650
#define IDS_RACESELECT_SOLARIAN         1651
#define IDS_RACESELECT_VYRIUM           1652
#define IDS_UNITS_MINIMAL               1653
#define IDS_UNITS_MEDIUM                1654
#define IDS_UNITS_HEAVY                 1655
#define IDS_GAMETYPE_GREED              1656
#define IDS_PLAYERSELECT_1              1657
#define IDS_PLAYERSELECT_2              1658
#define IDS_PLAYERSELECT_3              1659
#define IDS_PLAYERSELECT_4              1660
#define IDS_PLAYERSELECT_5              1661
#define IDS_PLAYERSELECT_6              1662
#define IDS_PLAYERSELECT_7              1663
#define IDS_PLAYERSELECT_8              1664
#define IDS_MAPTYPE_USERDEFINED         1665
#define IDS_FORMAT_PLAYER               1666
#define IDS_FORMAT_CAMPAIGN             1667
#define IDS_FORMAT_MISSION              1668
#define IDS_TCP_LAN                     1669
#define IDS_GAS_LOW                     1670
#define IDS_GAS_MEDIUM                  1671
#define IDS_GAS_HIGH                    1672
#define IDS_METAL_LOW                   1673
#define IDS_METAL_MEDIUM                1674
#define IDS_METAL_HIGH                  1675
#define IDS_CREW_LOW                    1676
#define IDS_CREW_MEDIUM                 1677
#define IDS_CREW_HIGH                   1678
#define IDS_VISIBILITY_EXPLORED         1679
#define IDS_VISIBILITY_NORMAL           1680
#define IDS_MISSION_SUCCESS             1681
#define IDS_MISSION_FAILURE             1682
#define IDS_MISSION_PRESSOK             1683
#define IDS_VISIBILITY_NONE             1684
#define IDS_CANT_DELETE                 1685
#define IDS_MAPTYPE_RING                1686
#define IDS_MAPTYPE_STAR                1687
#define IDS_MAPTYPE_NEW_RANDOM          1688
#define IDS_BEGIN_SCROLLING_TEXT        1700
#define IDS_FORMAT_PLAYERRESIGNED       1701
#define IDS_FORMAT_PLAYEROUT            1702
#define IDS_FORMAT_PLAYERLEFT           1703
#define IDS_FORMAT_PAUSE_DENIED         1704
#define IDS_MAX_PAUSE_EXCEEDED          1705
#define IDS_QUICKLOAD_FAILED            1706
#define IDS_QUICKLOAD_SUCCESS           1707
#define IDS_QUICKSAVE_SUCCESS           1708
#define IDS_QUICKLOAD_WAIT              1709
#define IDS_MESSAGE_ALLY_FRIEND         1710
#define IDS_MESSAGE_ALLY_ENEMY          1711
#define IDS_MESSAGE_ALLY_BOTH           1712
#define IDS_AI_RESIGN                   1750
#define IDS_AI_NEVERMIND                1751
#define IDS_AI_GIFT                     1752
#define IDS_AI_TERRAN_ATTACK_1          1753
#define IDS_AI_TERRAN_ATTACK_2          1754
#define IDS_AI_TERRAN_ATTACK_3          1755
#define IDS_AI_MANTIS_ATTACK_1          1756
#define IDS_AI_MANTIS_ATTACK_2          1757
#define IDS_AI_CELERY_ATTACK_1          1758
#define IDS_AI_CELERY_ATTACK_2          1759
#define IDS_AI_TERRAN_CELEBRATE_1       1760
#define IDS_AI_TERRAN_CELEBRATE_2       1761
#define IDS_AI_TERRAN_CELEBRATE_3       1762
#define IDS_AI_MANTIS_CELEBRATE_1       1763
#define IDS_AI_MANTIS_CELEBRATE_2       1764
#define IDS_AI_CELERY_CELEBRATE_1       1765
#define IDS_AI_CELERY_CELEBRATE_2       1766
#define IDS_AI_TERRAN_SAD_1             1767
#define IDS_AI_TERRAN_SAD_2             1768
#define IDS_AI_TERRAN_SAD_3             1769
#define IDS_AI_MANTIS_SAD_1             1770
#define IDS_AI_MANTIS_SAD_2             1771
#define IDS_AI_CELERY_SAD_1             1772
#define IDS_AI_CELERY_SAD_2             1773
#define IDS_AI_MANTIS_RESIGN            1774
#define IDS_AI_CELERY_RESIGN            1775
#define IDS_MISSION_DESC_BEGIN          1800
#define IDS_MISSION_DESC_1              1801
#define IDS_MISSION_DESC_2              1802
#define IDS_MISSION_DESC_3              1803
#define IIDS_MISSION_DESC_4             1804
#define IDS_MISSION_DESC_5              1805
#define IDS_MISSION_DESC_6              1806
#define IDS_MISSION_DESC_7              1807
#define IDS_MISSION_DESC_8              1808
#define IDS_MISSION_DESC_9              1809
#define IDS_MISSION_DESC_10             1810
#define IDS_MISSION_DESC_11             1811
#define IDS_MISSION_DESC_12             1812
#define IDS_MISSION_DESC_13             1813
#define IDS_MISSION_DESC_14             1814
#define IDS_MISSION_DESC_15             1815
#define IDS_MISSION_DESC_16             1816
#define IDS_MOVIE_DESC_BEGIN            1817
#define IDS_MOVIE_DESC_1                1818
#define IDS_MOVIE_DESC_2                1819
#define IDS_MOVIE_DESC_3                1820
#define IDS_MOVIE_DESC_4                1821
#define IDS_MOVIE_DESC_0                1822
#define IDS_MOVIE_DESC5                 1823
#define IDS_MOVIE_DESC_5                1823
#define IDS_MISSION_TITLE_BEGIN         1824
#define IDS_MISSION_TITLE1              1825
#define IDS_MISSION_TITLE2              1826
#define IDS_MISSION_TITLE3              1827
#define IDS_MISSION_TITLE4              1828
#define IDS_MISSION_TITLE5              1829
#define IDS_MISSION_TITLE6              1830
#define IDS_MISSION_TITLE7              1831
#define IDS_MISSION_TITLE8              1832
#define IDS_MISSION_TITLE9              1833
#define IDS_MISSION_TITLE10             1834
#define IDS_MISSION_TITLE11             1835
#define IDS_MISSION_TITLE12             1836
#define IDS_MISSION_TITLE13             1837
#define IDS_MISSION_TITLE14             1838
#define IDS_MISSION_TITLE15             1839
#define IDS_MISSION_TITLE16             1840
#define IDS_MOVIE_TITLE_BEGIN           1841
#define IDS_MOVIE_TITLE1                1842
#define IDS_MOVIE_TITLE2                1843
#define IDS_MOVIE_TITLE3                1844
#define IDS_MOVIE_TITLE4                1845
#define IDS_MOVIE_TITLE0                1846
#define IDS_MOVIE_TITLE5                1847
#define IDS_SAVE_QSMISSION              1848
#define IDS_SAVE_QSQUICKBATTLE          1849
#define IDS_TAB_BEGIN                   1900
#define IDS_TAB_PLAYER                  1901
#define IDS_TAB_GRAPHICS                1902
#define IDS_TAB_SOUNDS                  1903
#define IDS_TAB_TOTALS                  1904
#define IDS_TAB_UNITS                   1905
#define IDS_TAB_BUILDINGS               1906
#define IDS_TAB_TERRITORY               1907
#define IDS_TAB_RESOURCES               1908
#define IDS_TOOLBAR_TITLE_STRINGS       2000
#define IDS_TOOLBAR_GROUP               2001
#define IDS_TOOLBAR_LIKE_GROUP          2002
#define IDS_TOOLBAR_NOTHING             2003
#define IDS_PROG_BEGIN                  2100
#define IDS_PROG_INITMAP                2101
#define IDS_PROG_GENSYSTEMS             2102
#define IDS_PROG_RATESYSTEMS            2103
#define IDS_PROG_SELECTTHEME            2104
#define IDS_PROG_CREATESUB              2105
#define IDS_PROG_POPULATE               2106
#define IDS_PROG_ASSIGNPLAYERS          2107
#define IDS_PROG_LOADINTERFACE          2108
#define IDS_PROG_STARTAI                2109
#define IDS_PROG_INIT3D                 2110
#define IDS_PROG_CREATEAI               2111
#define IDS_PROG_CAMERA                 2112
#define IDS_PROG_OBJECTS                2113
#define IDS_PROG_MATRIX                 2114
#define IDS_PROG_SCRIPTS                2115
#define IDS_SCORE_DESC_BEGIN            2200
#define IDS_SCORE_DESC1                 2201
#define IDS_SCORE_DESC2                 2202
#define IDS_SCORE_DESC3                 2203
#define IDS_SCORE_DESC4                 2204
#define IDS_NUMBERS_BEGIN               2300
#define IDS_NUMBERS_0                   2301
#define IDS_NUMBERS_1                   2302
#define IDS_NUMBERS_2                   2303
#define IDS_NUMBERS_3                   2304
#define IDS_NUMBERS_4                   2305
#define IDS_NUMBERS_5                   2306
#define IDS_NUMBERS_6                   2307
#define IDS_NUMBERS_7                   2308
#define IDS_NUMBERS_8                   2309
#define IDS_NUMBERS_9                   2310
#define IDS_NUMBERS_10                  2311
#define IDS_NUMBERS_11                  2312
#define IDS_NUMBERS_12                  2313
#define IDS_NUMBERS_13                  2314
#define IDS_NUMBERS_14                  2315
#define IDS_NUMBERS_15                  2316
#define IDS_NUMBERS_16                  2317
#define IDS_CHEATS_BEGIN                2400
#define IDS_CHEATS_ENABLE               2401
#define IDS_CHEATS_VICTORY              2402
#define IDS_CHEATS_DEFEAT               2403
#define IDS_CHEATS_SKIP                 2404
#define IDS_CHEATS_QUICKBUILD           2405
#define IDS_CHEATS_FREE                 2406
#define IDS_CHEATS_KILLPLAYER           2407
#define IDS_CHEATS_FOGOFF               2408
#define IDS_CHEATS_FOGON                2409
#define IDS_CHEATS_DISCOVERY            2410
#define IDS_CHEATS_ORE                  2411
#define IDS_CHEATS_GAS                  2412
#define IDS_CHEATS_CREW                 2413
#define IDS_CHEATS_RESOURCES            2414
#define IDS_CHEATS_DEMO1                2415
#define IDS_CHEATS_DEMO2                2416
#define IDS_CHEATS_WON                  2417
#define IDS_CHEATS_LOST                 2418
#define IDS_CHEATS_UNLOCK               2419
#define IDS_CHEATS_BUILDON              2420
#define IDS_CHEATS_BUILDOFF             2421
#define IDS_CHEATS_COSTOFF              2422
#define IDS_CHEATS_COSTON               2423
#define IDS_CHEATS_DESTROY              2424
#define IDS_STRING3000                  3000
#define IDS_HINT_BUILDDEFAULT           3001
#define IDS_HINT_RESEARCHDEFAULT        3002
#define IDS_HINT_FIELDDEFAULT           3003
#define IDS_HINT_FIELD_ION              3004
#define IDS_HINT_BUILD_CORVETTE         3005
#define IDS_HINT_BUILD_MISSILECRUISER   3006
#define IDS_HINT_BUILD_LSAT             3007
#define IDS_HINT_BUILD_TANKER           3008
#define IDS_HINT_BUILD_TROOPSHIP        3009
#define IDS_HINT_BUILD_REFINERY         3010
#define IDS_HINT_BUILD_LIGHTIND         3011
#define IDS_HINT_FIELD_PLASMA           3012
#define IDS_HINT_ASTEROID               3013
#define IDS_HINT_FIELD_ASTEROID         3013
#define IDS_HINT_FIELD_ASTEROID_SML     3013
#define IDS_HINT_BUILD_FLEETCARRIER     3014
#define IDS_HINT_BUILD_BATTLESHIP       3015
#define IDS_HINT_BUILD_SPACESTATION     3016
#define IDS_HINT_BUILD_DREADNOUGHT      3017
#define IDS_HINT_BUILD_INFILTRATOR      3018
#define IDS_HINT_BUILD_LANCERCRUISER    3019
#define IDS_HINT_BUILD_SUPPLYSHIP       3020
#define IDS_HINT_BUILD_FABRICATOR       3021
#define IDS_HINT_BUILD_ADVFABRICATOR    3022
#define IDS_HINT_BUILD_FLEETADMIRAL     3023
#define IDS_HINT_BUILD_SUPPLYDEPOT      3024
#define IDS_HINT_BUILD_OUTPOST          3025
#define IDS_HINT_BUILD_LASERTURRET      3026
#define IDS_HINT_BUILD_NAVALACADEMY     3027
#define IDS_HINT_BUILD_MRSENSOR         3028
#define IDS_HINT_BUILD_ADVHULL          3029
#define IDS_HINT_BUILD_PROPLAB          3030
#define IDS_HINT_BUILD_REPAIRDEPOT      3031
#define IDS_HINT_BUILD_HEAVYIND         3032
#define IDS_HINT_BUILD_AWSLAB           3033
#define IDS_HINT_BUILD_DEFENSEBATTERY   3034
#define IDS_HINT_BUILD_LRSENSOR         3035
#define IDS_HINT_BUILD_LOGISTICS        3036
#define IDS_HINT_BUILD_NANOMETAL        3037
#define IDS_HINT_BUILD_TECHIND          3038
#define IDS_HINT_BUILD_FORCEWAVE        3039
#define IDS_HINT_FIELD_ANTIMATTER       3040
#define IDS_HINT_BUILD_HQ               3041
#define IDS_HINT_BUILD_BALLISTICSLAB    3042
#define IDS_HINT_BUILD_TENDER           3043
#define IDS_HINT_BUILD_HANGER           3044
#define IDS_HINT_BUILD_SENSORTOWER      3045
#define IDS_HINT_BUILD_DISPLACEMENTLAB  3046
#define IDS_HINT_BUILD_IONCANNON        3047
#define IDS_HINT_BUILD_HVYREFINERY      3048
#define IDS_HINT_BUILD_COCOON           3049
#define IDS_HINT_BUILD_COLLECTOR        3050
#define IDS_HINT_BUILD_GRCOLLECTOR      3051
#define IDS_HINT_BUILD_JUMPGATE         3052
#define IDS_HINT_BUILD_WARLORD          3053
#define IDS_HINT_BUILD_THRIPID          3054
#define IDS_HINT_BUILD_NIAD             3055
#define IDS_HINT_BUILD_PLANTATION       3056
#define IDS_HINT_BUILD_DISSECTION       3057
#define IDS_HINT_BUILD_BLASTFURNACE     3058
#define IDS_HINT_BUILD_EXPLORANGE       3059
#define IDS_HINT_BUILD_EYESTALK         3060
#define IDS_HINT_BUILD_MUTATION         3061
#define IDS_HINT_BUILD_BIOFORGE         3062
#define IDS_HINT_BUILD_FUSIONMILL       3063
#define IDS_HINT_BUILD_CARAPACE         3064
#define IDS_HINT_BUILD_HYBRID           3065
#define IDS_HINT_BUILD_CARRIONROOST     3066
#define IDS_HINT_BUILD_PLASMASPITTER    3067
#define IDS_HINT_BUILD_PLASMAHIVE       3068
#define IDS_HINT_BUILD_VORAAK           3069
#define IDS_HINT_BUILD_WEEVER           3070
#define IDS_HINT_BUILD_ZORAP            3071
#define IDS_HINT_BUILD_SIPHON           3072
#define IDS_HINT_BUILD_FRIGATE          3073
#define IDS_HINT_BUILD_SCOUTCARRIER     3074
#define IDS_HINT_BUILD_KHAMIR           3075
#define IDS_HINT_BUILD_SPINELAYER       3076
#define IDS_HINT_BUILD_LEECH            3077
#define IDS_HINT_BUILD_HIVECARRIER      3078
#define IDS_HINT_BUILD_SCARAB           3079
#define IDS_HINT_BUILD_TIAMAT           3080
#define IDS_HINT_BUTTON_RESEARCH        3081
#define IDS_HINT_BUTTON_SHIPYARD        3082
#define IDS_HINT_BUTTON_NONGUNBOAT      3083
#define IDS_HINT_BUTTON_FLEETS          3084
#define IDS_HINT_BUTTON_DIPLOMACY       3085
#define IDS_HINT_BUTTON_CHAT            3086
#define IDS_HINT_BUTTON_OPTIONS         3087
#define IDS_HINT_BUTTON_SUPPLY          3088
#define IDS_HINT_BUTTON_GAS             3089
#define IDS_HINT_BUTTON_ORE             3090
#define IDS_HINT_BUTTON_CREW            3091
#define IDS_HINT_BUTTON_ATTACK          3092
#define IDS_HINT_BUTTON_DEFEND          3093
#define IDS_HINT_BUTTON_STAND           3094
#define IDS_HINT_BUTTON_IDLE            3095
#define IDS_HINT_BUTTON_STOP            3096
#define IDS_HINT_BUTTON_PATROL          3097
#define IDS_HINT_BUTTON_ESCORT          3098
#define IDS_HINT_BUTTON_GOTO            3099
#define IDS_HINT_BUTTON_SELL            3100
#define IDS_HINT_BUTTON_RALLY           3101
#define IDS_HINT_MAP_SYSTEM             3102
#define IDS_HINT_MAP_SECTOR             3103
#define IDS_HINT_MAP_ROTATERIGHT        3104
#define IDS_HINT_MAP_ROTATELEFT         3105
#define IDS_HINT_MAP_RESTORE            3106
#define IDS_HINT_MAP_STARMAP            3107
#define IDS_HINT_TOOLBAR_MIN            3108
#define IDS_HINT_TOOLBAR_MAX            3109
#define IDS_HINT_UPGRADE_TENDER1        3110
#define IDS_HINT_UPGRADE_TENDER2        3111
#define IDS_HINT_UPGRADE_SUPPLY1        3112
#define IDS_HINT_UPGRADE_SUPPLY2        3113
#define IDS_HINT_FIELD_CELSIUS          3114
#define IDS_HINT_UPGRADE_SENSOR1        3115
#define IDS_HINT_UPGRADE_SENSOR2        3116
#define IDS_HINT_FIELD_ASTEROID_MED     3117
#define IDS_HINT_FIELD_ASTEROID_LG      3118
#define IDS_HINT_UPGRADE_SENSOR3        3119
#define IDS_HINT_UPGRADE_SENSOR4        3120
#define IDS_HINT_FIELD_HELIOS           3121
#define IDS_HINT_FIELD_CYGNUS           3122
#define IDS_HINT_FIELD_HYADES           3123
#define IDS_HINT_FIELD_LITHIUM          3124
#define IDS_HINT_FIELD_ANTI_NEBULA      3125
#define IDS_HINT_FIELD_BLACKHOLE        3126
#define IDS_HINT_FIELD_DEBRIS           3127
#define IDS_HINT_FIELD_ORENUGGET        3128
#define IDS_HINT_FIELD_GASNUGGET        3129
#define IDS_HINT_UPGRADE_WEAPON1        3130
#define IDS_HINT_UPGRADE_WEAPON2        3131
#define IDS_HINT_UPGRADE_WEAPON3        3132
#define IDS_HINT_UPGRADE_WEAPON4        3133
#define IDS_HINT_UPGRADE_HARVESTER1     3134
#define IDS_HINT_UPGRADE_HARVESTER2     3135
#define IDS_HINT_UPGRADE_TROOPSHIP1     3136
#define IDS_HINT_UPGRADE_TROOPSHIP2     3137
#define IDS_HINT_UPGRADE_TROOPSHIP3     3138
#define IDS_HINT_UPGRADE_FLEET1         3139
#define IDS_HINT_UPGRADE_FLEET2         3140
#define IDS_HINT_UPGRADE_FLEET3         3141
#define IDS_HINT_UPGRADE_FLEET4         3142
#define IDS_HINT_UPGRADE_MISSILE1       3143
#define IDS_HINT_UPGRADE_MISSILE2       3144
#define IDS_HINT_UPGRADE_HULL1          3145
#define IDS_HINT_UPGRADE_HULL2          3146
#define IDS_HINT_UPGRADE_HULL3          3147
#define IDS_HINT_UPGRADE_HULL4          3148
#define IDS_HINT_UPGRADE_SHIELD1        3149
#define IDS_HINT_UPGRADE_SHIELD2        3150
#define IDS_HINT_UPGRADE_SHIELD3        3151
#define IDS_HINT_UPGRADE_SHIELD4        3152
#define IDS_HINT_UPGRADE_ENGINE1        3153
#define IDS_HINT_UPGRADE_ENGINE2        3154
#define IDS_HINT_UPGRADE_ENGINE3        3155
#define IDS_HINT_UPGRADE_ENGINE4        3156
#define IDS_HINT_UPGRADE_FIGHTER1       3157
#define IDS_HINT_UPGRADE_FIGHTER2       3158
#define IDS_HINT_UPGRADE_FIGHTER3       3159
#define IDS_HINT_SPECIAL_CLOAK          3160
#define IDS_HINT_SPECIAL_TEMPEST        3161
#define IDS_HINT_SPECIAL_PROBE          3162
#define IDS_HINT_SPECIAL_VAMPIRE        3163
#define IDS_HINT_SPECIAL_AEGIS          3164
#define IDS_HINT_UPGRADE_ORE1           3165
#define IDS_HINT_UPGRADE_ORE2           3166
#define IDS_HINT_UPGRADE_GAS1           3167
#define IDS_HINT_UPGRADE_GAS2           3168
#define IDS_HINT_UPGRADE_FIGHTER4       3169
#define IDS_HINT_UPGRADE_FIGHTER5       3170
#define IDS_HINT_UPGRADE_SUPPLY3        3171
#define IDS_HINT_UPGRADE_SUPPLY4        3172
#define IDS_HINT_UPGRADE_SUPPLY5        3173
#define IDS_HINT_UPGRADE_ORE3           3174
#define IDS_HINT_UPGRADE_GAS3           3175
#define IDS_HINT_BUILD_SEEKER           3176
#define IDS_HINT_UPGRADE_SIPHON1        3177
#define IDS_HINT_UPGRADE_SIPHON2        3178
#define IDS_HINT_UPGRADE_PLANTATION1    3179
#define IDS_HINT_UPGRADE_PLANTATION2    3180
#define IDS_HINT_UPGRADE_PLANTATION3    3181
#define IDS_HINT_UPGRADE_EXPLORAM1      3182
#define IDS_HINT_UPGRADE_EXPLORAM2      3183
#define IDS_HINT_SPECIAL_MIMIC          3184
#define IDS_HINT_SPECIAL_REPELLCLOUD    3185
#define IDS_HINT_SPECIAL_GRAVWELL       3186
#define IDS_HINT_SPECIAL_REPULSEBEAM    3187
#define IDS_HINT_UPGRADE_SIPHON3        3188
#define IDS_HINT_EVOLUTION_GRCOLLECTOR  3189
#define IDS_HINT_EVOLUTION_NIAD         3190
#define IDS_HINT_EVOLUTION_EXPLORANGE   3191
#define IDS_HINT_EVOLUTION_MUTACOLONY   3192
#define IDS_HINT_EVOLUTION_FUSION       3193
#define IDS_HINT_EVOLUTION_CARAPACE     3194
#define IDS_HINT_EVOLUTION_HYBRID       3195
#define IDS_HINT_EVOLUTION_PLASMAHIVE   3196
#define IDS_HINT_EVOLUTION_VORAAK       3197
#define IDS_HINT_UPGRADE_REPAIR         3198
#define IDS_HINT_UPGRADE_ENGINE5        3199
#define IDS_HINT_UPGRADE_HULL5          3200
#define IDS_HINT_UPGRADE_WEAPON5        3201
#define IDS_HINT_UPGRADE_SHIELD5        3202
#define IDS_HINT_UPGRADE_FLEET5         3203
#define IDS_HINT_UPGRADE_GALIOT1        3204
#define IDS_HINT_UPGRADE_GALIOT2        3205
#define IDS_HINT_UPGRADE_EUTROMIL1      3206
#define IDS_HINT_UPGRADE_EUTROMIL2      3207
#define IDS_HINT_UPGRADE_SENSOR5        3208
#define IDS_HINT_UPGRADE_LEGIONAIRE1    3209
#define IDS_HINT_UPGRADE_LEGIONAIRE2    3210
#define IDS_HINT_UPGRADE_LEGIONAIRE3    3211
#define IDS_HINT_UPGRADE_LEGIONAIRE4    3212
#define IDS_HINT_BUILD_ACROPOLIS        3213
#define IDS_HINT_BUILD_OXIDATOR         3214
#define IDS_HINT_BUILD_SENTINEL         3215
#define IDS_HINT_BUILD_PAVILION         3216
#define IDS_HINT_BUILD_BUNKER           3217
#define IDS_HINT_BUILD_HELIONVEIL       3218
#define IDS_HINT_BUILD_ESPCOIL          3219
#define IDS_HINT_BUILD_CITADEL          3220
#define IDS_HINT_BUILD_EUTROMIL         3221
#define IDS_HINT_BUILD_GRPAVILION       3222
#define IDS_HINT_BUILD_PROTEUS          3223
#define IDS_HINT_BUILD_XENO             3224
#define IDS_HINT_BUILD_MUNITIONS        3225
#define IDS_HINT_BUILD_ANVIL            3226
#define IDS_HINT_BUILD_TURBINE          3227
#define IDS_HINT_BUILD_HYDROFOIL        3228
#define IDS_HINT_BUILD_TALOREAN         3229
#define IDS_HINT_BUILD_STARBURST        3230
#define IDS_HINT_BUILD_PORTAL           3231
#define IDS_HINT_BUILD_TAOS             3232
#define IDS_HINT_BUILD_FORGER           3233
#define IDS_HINT_BUILD_STRATUM          3234
#define IDS_HINT_BUILD_GALIOT           3235
#define IDS_HINT_BUILD_ORACLE           3236
#define IDS_HINT_BUILD_AURORA           3237
#define IDS_HINT_BUILD_LEGIONAIRE       3238
#define IDS_HINT_BUILD_POLARIS          3239
#define IDS_HINT_BUILD_ATLAS            3240
#define IDS_HINT_BUILD_TRIREME          3241
#define IDS_HINT_BUILD_MONOLITH         3242
#define IDS_HINT_SPECIAL_SYNTHESIS      3243
#define IDS_HINT_SPECIAL_DISRUPTOR      3244
#define IDS_HINT_SPECIAL_AURORACLOAK    3245
#define IDS_HINT_SPECIAL_DESTABILIZE    3246
#define IDS_HINT_SPECIAL_TRACTORBEAM    3247
#define IDS_HINT_BUILD_HALSEY           3248
#define IDS_HINT_BUILD_HAWKES           3249
#define IDS_HINT_BUILD_BENSON           3250
#define IDS_HINT_BUILD_SMIRNOFF         3251
#define IDS_HINT_BUILD_STEELE           3252
#define IDS_HINT_BUILD_TAKAI            3253
#define IDS_HINT_BUILD_MORDELLA         3254
#define IDS_HINT_BUILD_AZKAR            3255
#define IDS_HINT_BUILD_VERLAK           3256
#define IDS_HINT_BUILD_KERTAK           3257
#define IDS_HINT_BUILD_ADTHRIPID        3258
#define IDS_HINT_BUILD_MALKOR           3259
#define IDS_HINT_BUILD_BLANUS           3260
#define IDS_HINT_BUILD_ELAN             3261
#define IDS_HINT_BUILD_VIVAC            3262
#define IDS_HINT_BUILD_JOULE            3263
#define IDS_HINT_BUILD_PROCYO           3264
#define IDS_HINT_BUILD_NATUS            3265
#define IDS_HINT_UPGRADE_LEECH1         3266
#define IDS_HINT_UPGRADE_LEECH2         3267
#define IDS_HINT_BUTTON_SUPPON          3268
#define IDS_HINT_BUTTON_SUPPOFF         3269
#define IDS_HINT_BUTTON_AUTOSUPP        3270
#define IDS_HINT_BUTTON_CLOAK           3271
#define IDS_HINT_SPECIAL_PING           3272
#define IDS_HINT_SPECIAL_EXPLORAM       3273
#define IDS_HINT_SPECIAL_EXPLOMINES     3274
#define IDS_HINT_UPGRADE_PMISSILE1      3275
#define IDS_HINT_UPGRADE_PMISSILE2      3276
#define IDS_HINT_UPGRADE_CWEAPON1       3277
#define IDS_HINT_UPGRADE_CWEAPON2       3278
#define IDS_HINT_UPGRADE_CWEAPON3       3279
#define IDS_HINT_UPGRADE_CWEAPON4       3280
#define IDS_HINT_UPGRADE_CWEAPON5       3281
#define IDS_HINT_UPGRADE_CORE1          3282
#define IDS_HINT_UPGRADE_CORE2          3283
#define IDS_HINT_UPGRADE_CGAS1          3284
#define IDS_HINT_UPGRADE_CGAS2          3285
#define IDS_HINT_SPECIAL_CPING          3286
#define IDS_HINT_UPGRADE_CSUPPLY1       3287
#define IDS_HINT_UPGRADE_CSUPPLY2       3288
#define IDS_HINT_UPGRADE_CSUPPLY3       3289
#define IDS_HINT_UPGRADE_CSUPPLY4       3290
#define IDS_HINT_UPGRADE_CSUPPLY5       3291
#define IDS_HINT_SPECIAL_MPING          3292
#define IDS_HINT_UPGRADE_MWEAPON1       3293
#define IDS_HINT_UPGRADE_MWEAPON2       3294
#define IDS_HINT_UPGRADE_MWEAPON3       3295
#define IDS_HINT_UPGRADE_MFIGHTER1      3296
#define IDS_HINT_UPGRADE_MFIGHTER2      3297
#define IDS_HINT_UPGRADE_MFIGHTER3      3298
#define IDS_HINT_UPGRADE_MFIGHTER4      3299
#define IDS_HINT_UPGRADE_MFIGHTER5      3300
#define IDS_HINT_UPGRADE_MSUPPLY1       3301
#define IDS_HINT_UPGRADE_MSUPPLY2       3302
#define IDS_HINT_UPGRADE_MSUPPLY3       3303
#define IDS_HINT_UPGRADE_CORE3          3304
#define IDS_HINT_UPGRADE_CGAS3          3305
#define IDS_HINT_TEXT_ORE               3306
#define IDS_HINT_TEXT_GAS               3307
#define IDS_HINT_TEXT_CREW              3308
#define IDS_HINT_TEXT_CP                3309
#define IDS_HINT_TEXT_DISABLED          3310
#define IDS_HINT_SPECIAL_AD_CLOAKT      3311
#define IDS_HINT_SPECIAL_AD_TEMPEST     3312
#define IDS_HINT_SPECIAL_AD_PROBE       3313
#define IDS_HINT_SPECIAL_AD_VAMPIRE     3314
#define IDS_HINT_SPECIAL_AD_AEGIS       3315
#define IDS_HINT_SPECIAL_AD_MIMIC       3316
#define IDS_HINT_SPECIAL_AD_REPELLCLOUD 3317
#define IDS_HINT_SPECIAL_AD_GRAVWELL    3318
#define IDS_HINT_SPECIAL_AD_REPULSEWAVE 3319
#define IDS_HINT_SPECIAL_AD_RAM         3320
#define IDS_HINT_SPECIAL_AD_SYNTHESIS   3321
#define IDS_HINT_SPECIAL_AD_DISRUPTOR   3322
#define IDS_HINT_SPECIAL_AD_SHROUD      3323
#define IDS_HINT_SPECIAL_AD_DESTABILIZE 3324
#define IDS_HINT_SPECIAL_AD_AUGERRAY    3325
#define IDS_HINT_SPECIAL_AD_CLOAKS      3326
#define IDS_HINT_ADMIRAL_FORMFLEET      3327
#define IDS_HINT_ADMIRAL_DISBANDFLEET   3328
#define IDS_HINT_ADMIRAL_REPAIR         3329
#define IDS_HINT_ADMIRAL_RESUPPLY       3330
#define IDS_HINT_ADMIRAL_TRANSFER       3331
#define IDS_HINT_ADMIRAL_ASSAULT        3332
#define IDS_HINT_F_STANCE_NORMAL        3333
#define IDS_HINT_F_STANCE_PATROL        3334
#define IDS_HINT_AT_PEACE               3335
#define IDS_HINT_AT_DEFEND              3336
#define IDS_HINT_AT_HOLD                3337
#define IDS_HINT_AT_SEEK                3338
#define IDS_BEGIN_MISSIONS              4000
#define IDS_BEGIN_TERRAN_MISSIONS       4000
#define IDS_TMISSION_1                  4001
#define IDS_TMISSION_2                  4002
#define IDS_TMISSION_3                  4003
#define IDS_TMISSION_4                  4004
#define IDS_TMISSION_5                  4005
#define IDS_TMISSION_6                  4006
#define IDS_TMISSION_7                  4007
#define IDS_TMISSION_8                  4008
#define IDS_TMISSION_9                  4009
#define IDS_TMISSION_10                 4010
#define IDS_TMISSION_11                 4011
#define IDS_TMISSION_12                 4012
#define IDS_BEGIN_MANTIS_MISSIONS       4100
#define IDS_ALERT_UNKNOWN               4200
#define IDS_ALERT_UNDER_ATTACK          4201
#define IDS_ALERT_ENEMY_SIGHTED         4202
#define IDS_ALERT_OUT_SUPPLY            4203
#define IDS_ALERT_UNIT_BUILT            4204
#define IDS_ALERT_PLATFORM_BUILD        4205
#define IDS_ALERT_RESOURCE_EXAHAUSTED   4206
#define IDS_ALERT_RESEARCH_COMPLETE     4207
#define IDS_ALERT_MUTATION_COMPLETE     4208
#define IDS_ALERT_ADMIRAL_LOST          4209
#define IDS_ALERT_ADMIRAL_MESSAGE       4210
#define IDS_ALERT_ALLIED_ATTACK         4211
#define IDS_ALERT_MISSION               4212
#define IDS_BEGIN_SUBTITLES             4500
#define IDS_SUB_DEATH                   4501
#define IDS_SUB_ENEMY_SIGHTED           4502
#define IDS_SUB_UNDERATTACK             4503
#define IDS_SUB_NOSUPPLIES              4504
#define IDS_SUB_MOVE                    4505
#define IDS_SUB_DENIED                  4506
#define IDS_SUB_SPECIAL_ATTACK          4507
#define IDS_SUB_ATTACK                  4508
#define IDS_SUB_HAR_DEPLETED            4509
#define IDS_SUB_NO_CP                   4510
#define IDS_SUB_NO_GAS                  4511
#define IDS_SUB_NO_CREW                 4512
#define IDS_SUB_NO_METAL                4513
#define IDS_SUB_NO_BUILD                4514
#define IDS_SUB_ADMIRAL_ON_DECK         4515
#define IDS_SUB_ADMIRAL_OFF_DECK        4516
#define IDS_SUB_ADMIRAL_TRANS_FAIL      4517
#define IDS_SUB_ADMIRAL_FLAG_DANGER     4518
#define IDS_SUB_FLEET_75_DAMAGE         4519
#define IDS_SUB_FLEET_50_DAMAGE         4520
#define IDS_SUB_FLEET_LOW_SUPPLIES      4521
#define IDS_SUB_BATTLE_GOOD             4522
#define IDS_SUB_BATTLE_BLEAK            4523
#define IDS_SUB_BATTLE_MODERATE         4524
#define IDS_SUB_SCUTTLE                 4525
#define IDS_SUB_RESUPPLY                4526
#define IDS_SUB_SELECT                  4527
#define IDS_SUB_CONSTRUCTION_COMP       4528
#define IDS_SUB_ALLIED_ATTACK           4529
#define IDS_SUB_RES_MIMIC               4530
#define IDS_SUB_RES_ENGINE              4531
#define IDS_SUB_RES_FIGHTER             4532
#define IDS_SUB_RES_GRAVWELL            4533
#define IDS_SUB_RES_HULL                4534
#define IDS_SUB_RES_LEECH               4535
#define IDS_SUB_RES_RAM                 4536
#define IDS_SUB_RES_REPCLOUD            4537
#define IDS_SUB_RES_REP_WAVE            4538
#define IDS_SUB_RES_SENSOR              4539
#define IDS_SUB_RES_SHIELD              4540
#define IDS_SUB_RES_SUPPLY              4541
#define IDS_SUB_RES_SIPHON              4542
#define IDS_SUB_RES_RESUPPLY            4543
#define IDS_SUB_RES_WEAPON              4544
#define IDS_SUB_RES_SHROUD              4545
#define IDS_SUB_RES_DESTABILIZER        4546
#define IDS_SUB_RES_GAS                 4547
#define IDS_SUB_RES_LEGIONAIRE          4548
#define IDS_SUB_RES_MASS_DISRUPTOR      4549
#define IDS_SUB_RES_ORE                 4550
#define IDS_SUB_RES_PROTEUS             4551
#define IDS_SUB_RES_SYNTH               4552
#define IDS_SUB_RES_GALIOT              4553
#define IDS_SUB_RES_AUGER               4554
#define IDS_SUB_RES_TEMPEST             4555
#define IDS_SUB_RES_PROBE               4556
#define IDS_SUB_RES_AEGIS               4557
#define IDS_SUB_RES_VAMP                4558
#define IDS_SUB_RES_CLOAK               4559
#define IDS_SUB_RES_MISSILE             4560
#define IDS_SUB_RES_HARVESTER           4561
#define IDS_SUB_RES_TROOPSHIP           4562
#define IDS_SUB_UPGRADE                 4563
#define IDS_BEGIN_SYSTEM_NAMES          5000
#define IDS_SYSTEM_NAME_1               5001
#define IDS_SYSTEM_NAME_2               5002
#define IDS_SYSTEM_NAME_3               5003
#define IDS_SYSTEM_NAME_4               5004
#define IDS_SYSTEM_NAME_5               5005
#define IDS_SYSTEM_NAME_6               5006
#define IDS_SYSTEM_NAME_7               5007
#define IDS_SYSTEM_NAME_8               5008
#define IDS_SYSTEM_NAME_9               5009
#define IDS_SYSTEM_NAME_10              5010
#define IDS_SYSTEM_NAME_11              5011
#define IDS_SYSTEM_NAME_12              5012
#define IDS_SYSTEM_NAME_13              5013
#define IDS_SYSTEM_NAME_14              5014
#define IDS_SYSTEM_NAME_15              5015
#define IDS_SYSTEM_NAME_16              5016
#define IDS_SYSTEM_NAME_17              5017
#define IDS_SYSTEM_NAME_18              5018
#define IDS_SYSTEM_NAME_19              5019
#define IDS_SYSTEM_NAME_20              5020
#define IDS_SYSTEM_NAME_21              5021
#define IDS_SYSTEM_NAME_22              5022
#define IDS_SYSTEM_NAME_23              5023
#define IDS_SYSTEM_NAME_24              5024
#define IDS_BEGIN_PLANET_NAMES          5100
#define IDS_PLANET_NAME_1               5101
#define IDS_PLANET_NAME_2               5102
#define IDS_PLANET_NAME_3               5103
#define IDS_PLANET_NAME_4               5104
#define IDS_PLANET_NAME_5               5105
#define IDS_PLANET_NAME_6               5106
#define IDS_PLANET_NAME_7               5107
#define IDS_PLANET_NAME_8               5108
#define IDS_PLANET_NAME_9               5109
#define IDS_PLANET_NAME_10              5110
#define IDS_PLANET_NAME_11              5111
#define IDS_PLANET_NAME_12              5112
#define IDS_PLANET_NAME_13              5113
#define IDS_PLANET_NAME_14              5114
#define IDS_PLANET_NAME_15              5115
#define IDS_PLANET_NAME_16              5116
#define IDS_PLANET_NAME_17              5117
#define IDS_PLANET_NAME_18              5118
#define IDS_PLANET_NAME_19              5119
#define IDS_PLANET_NAME_20              5120
#define IDS_BANDWIDTH_NORMAL            5121
#define IDS_BANDWIDTH_BROADBAND         5122
#define IDS_BANDWIDTH                   5123
#define IDS_DELETE                      5124
#define IDS_DELETE_QUERY                5125
#define IDS_CQ2STRINGS                  6000
#define IDS_MT_LOCUS                    6001
#define IDS_MT_COALESCER                6002
#define IDS_MT_HATCHERY                 6003
#define IDS_MT_COCHLEA_DISH             6004
#define IDS_MT_COMPILER                 6005
#define IDS_MT_FORMULATOR               6006
#define IDS_MT_GUDGEON                  6007
#define IDS_MT_REPOSITORIUM             6008
#define IDS_MT_PERPETUATOR              6009
#define IDS_MT_CLAW_OF_VYRIE            6010
#define IDS_MT_EYE_OF_VYRIE             6011
#define IDS_MT_HAMMER_OF_VYRIE          6012
#define IDS_MT_SINUATOR                 6013
#define IDS_MT_CYNOSURE                 6014
#define IDS_MT_SHAPER                   6015
#define IDS_MT_ANACONDA                 6016
#define IDS_MT_AGGREGATOR               6017
#define IDS_MT_MYSTIC                   6018
#define IDS_MT_VIPER                    6019
#define IDS_MT_ADDER                    6020
#define IDS_MT_NECTROP                  6021
#define IDS_MT_ERTRAG                   6022
#define IDS_MT_MOK                      6023
#define IDS_MT_COBRA                    6024
#define IDS_MT_CROTAL                   6025
#define IDS_MT_BASILISK                 6026
#define IDS_MT_LEVIATHIAN               6027
#define IDS_MT_TEMPLE_OF_VYRIE          6028
#define IDS_MT_REPAIRSHIP               6100
#define IDS_MT_GEN_ADMIRAL              6200
#define IDS_MT_TMP_NOVABOMB             6300
#define IDS_MT_TMP_INTELLCTR            6301
#define IDS_MT_MP_RESOURCE              6302
#define IDS_MT_MP_RESEARCHLAB           6303
#define IDS_MT_MP_INDUSTRIAL            6304
#define IDS_MT_MMP_HEALINGCLOUD         6305
#define IDS_MT_MMP_BEEHIVE              6306
#define IDS_MT_CMP_CLOAKING             6307
#define IDS_MT_CMP_TALMATRIX            6308
#define IDS_MT_VMP_ASTEROID             6309
#define IDS_MT_VMP_SPACEFOLDER          6310
#define IDS_MT_ESPIONAGE                6311
#define IDS_MT_BLOCKADE_RUNNER          6312
#define IDS_MT_LISTENING_DEVICE         6313
#define IDS_MT_GENESIS_DEVICE           6314
#define IDS_TT_REQ_CQ2_Units            6500
#define IDS_TT_REQ_REPAIRSHIP           6501
#define IDS_TT_REPAIRSHIPREQUIRED       6501
#define IDS_TT_REQ_MP_RESOURCE          6503
#define IDS_TT_REQ_MP_RESEARCHLAB       6504
#define IDS_TT_REQ_MP_INDUSTRIAL        6505
#define IDS_TT_REQ_TMP_INTELLCTR        6506
#define IDS_TT_REQ_TMP_NOVABOMB         6507
#define IDS_TT_REQ_MMP_HEALINGCLOUD     6508
#define IDS_TT_REQ_MMP_BEEHIVE          6509
#define IDS_TT_REQ_CMP_CLOAKING         6510
#define IDS_TT_REQ_CMP_TALMATRIX        6511
#define IDS_TT_REQ_VMP_ASTEROID         6512
#define IDS_TT_REQ_VMP_SPACEFOLDER      6513
#define IDS_TT_REFINERY_ORE             6514
#define IDS_TT_REFINERY_GAS             6515
#define IDS_TT_MP_NOVA_BUTTON           6516
#define IDS_TT_HYBRID_DAVINCI_SHIELD    6517
#define IDS_TT_HYBRID_DAVINCI_WEAPON    6518
#define IDS_TT_HYBRID_DAVINCI_SENSOR    6519
#define IDS_STRING6529                  6600
#define IDS_TT_FORM_ATEASE              6601
#define IDS_TT_FORM_STANDASSAULT        6602
#define IDS_TT_FORM_BLOCKADE            6603
#define IDS_TT_FORM_CONVOY              6604
#define IDS_TT_FORM_HALSEYMAN           6605
#define IDS_TT_FORM_LANCER              6606
#define IDS_TT_FORM_PLANETDEF           6607
#define IDS_TT_FORM_MISSILERUSHDEF      6608
#define IDS_TT_FORM_MOBILEDEF           6609
#define IDS_TT_FORM_PLATOFF             6610
#define IDS_TT_FORM_REPAIR              6611
#define IDS_TT_FORM_SCOUT               6612
#define IDS_TT_FORM_SEEKDESTROY         6613
#define IDS_TT_KIT                      6700
#define IDS_TT_KIT_ANTICEL              6701
#define IDS_TT_KIT_ANTIMANTIS           6702
#define IDS_TT_KIT_ANTITERRAN           6703
#define IDS_TT_KIT_ANTIVYRIUM           6704
#define IDS_TT_TKIT_HALSEY              6705
#define IDS_TT_TKIT_LANCER              6706
#define IDS_TT_TKIT_LOGISTICS           6707
#define IDS_TT_TKIT_MISSILERUSH         6708
#define IDS_TT_TKIT_MOBILEDEF           6709
#define IDS_TT_TKIT_PLATOFF             6710
#define IDS_TT_TKIT_REPAIR              6711
#define IDS_TT_TKIT_SCOUT               6712
#define IDS_TT_TKIT_SEEKDESTROY         6713
#define IDS_TT_TKIT_TACTICS             6714
#define IDS_TT_KIT_ADMTAB               6715
#define IDS_STRING6716                  6800
#define IDS_HINT_BUILD_MP_INDUSTRIAL    6801
#define IDS_HINT_BUILD_MP_RESEARCHLAB   6802
#define IDS_HINT_BUILD_MP_RESOURCE      6803
#define IDS_HINT_BUILD_MP_INTELLCTR     6804
#define IDS_HINT_BUILD_MP_NOVABOMB      6805
#define IDS_HINT_BUILD_REPAIRSHIP       6806
#define IDS_HINT_BUILD_ESPIONAGE        6807
#define IDS_HINT_KIT_HALSEY             6808
#define IDS_HINT_KIT_LANCER             6809
#define IDS_HINT_KIT_LOGISTICS          6810
#define IDS_HINT_KIT_MISSILERUSH        6811
#define IDS_HINT_KIT_MOBILEDEF          6812
#define IDS_HINT_KIT_PLATOFF            6813
#define IDS_HINT_KIT_REPAIR             6814
#define IDS_HINT_KIT_SCOUT              6815
#define IDS_HINT_KIT_SEEKDESTROY        6816
#define IDS_HINT_KIT_TACTICS            6817
#define IDS_HINT_KIT_ANTICEL            6818
#define IDS_HINT_KIT_ANTIMANTIS         6819
#define IDS_HINT_KIT_ANTITERRAN         6820
#define IDS_HINT_KIT_ANTIVYRIUM         6821
#define IDS_HINT_FORM_ATEASE            6822
#define IDS_HINT_FORM_ASSAULT           6823
#define IDS_HINT_FORM_BLOCKADE          6824
#define IDS_HINT_FORM_CONVOY            6825
#define IDS_HINT_FORM_HALSEY            6826
#define IDS_HINT_FORM_LANCER            6827
#define IDS_HINT_FORM_PLANETDEF         6828
#define IDS_HINT_FORM_MISSILERUSH       6829
#define IDS_HINT_FORM_MOBILEDEF         6830
#define IDS_HINT_FORM_PLATOFF           6831
#define IDS_HINT_FORM_REPAIR            6832
#define IDS_HINT_FORM_SCOUT             6833
#define IDS_HINT_FORM_SEEKDESTROY       6834
#define IDS_NOVA_WARNING_30             6835
#define IDS_NOVA_WARNING_25             6836
#define IDS_NOVA_WARNING_20             6837
#define IDS_NOVA_WARNING_15             6838
#define IDS_NOVA_WARNING_10             6839
#define IDS_STRING6840                  6840
#define IDS_NOVA_WARNING_5              6840
#define IDS_HINT_SPECIAL_SENSORJAM      6841
#define IDS_HINT_SPECIAL_SHIELDJAM      6842
#define IDS_HINT_SPECWEAP_WEAPJAM       6843
#define IDS_HINT_SPECIAL_WEAPJAM        6843
#define IDS_MT_CQ2_UNITS                7000
#define IDS_MT_REAPIRSHIP               7100
#define IDS_STRING10000                 10000
#define IDS_DUMMY_MONEY                 10001
#define IDS_DUMMY_NAME                  10002
#define IDM_NEW_MISSION                 40008
#define IDM_OPEN_MISSION                40009
#define IDM_SAVE_MISSION                40010
#define IDM_SAVEAS_MISSION              40011
#define IDM_CLOSE_MISSION               40012
#define IDM_MRU0_MISSION                40017
#define IDM_MRU1_MISSION                40018
#define IDM_MRU2_MISSION                40019
#define IDM_MRU3_MISSION                40020
#define IDM_NO_AUTO_SAVE                40022
#define IDM_EDIT_PATH                   40024
#define IDM_MIN_LATENCY                 40028
#define IDM_NO_FRAME_LIMIT              40030
#define IDM_GAME_SPEED                  40031
#define IDM_POSTOOL_WORLD               40033
#define IDM_VOLUME_ADJUST               40036
#define IDM_EDITOR_MODE                 40037
#define IDM_DRAW_HOTRECTS               40038
#define IDM_VIEW_REALTIME               40039
#define ID_VIEW_EMPTY                   40041
#define IDM_VISIBILITY_RULES_OFF        40046
#define IDM_NET_STRESS                  40054
#define IDM_RUSE_RESET                  40057
#define IDM_RUSE_SAVE                   40058
#define IDM_RUSE_EXITMAPEDITOR          40059
#define IDM_ENABLE_RUSE                 40060
#define IDM_NOAUTOTARGET                40063
#define IDM_SHOWPARTS                   40065
#define IDM_PRINT_OPLIST                40066
#define IDM_NO_WINNING_CONDITIONS       40068
#define IDM_RELOAD_DATABASE             40071
#define IDM_RESET_VISIBILITY            40073
#define IDM_START_PROGRAM               40074
#define IDM_KILL_PROGRAM                40075
#define IDM_RESET_STARTFLAG             40076
#define IDM_RESET_CAMERA                40077
#define IDM_INFO_HIGHLIGHT              40078
#define IDM_QUICK_SAVE                  40079
#define IDM_QUICK_SAVE_AS               40080
#define IDM_EDITOR_DROP_OBJECT          40081
#define IDM_ENABLE_CHEATS               40082
#define IDH_SAVE_SYS_KIT                40083
#define IDH_LOAD_SYS_KIT                40084
#define IDM_NO_SUPPLIES                 40085
#define IDM_NO_DAMAGE                   40086
#define IDM_SHOW_GRIDS                  40087
#define IDM_ALL_TECH                    40088
#define IDM_LOAD_TERRAIN                40089
#define IDM_LOAD_FILTER                 40092
#define IDM_CHEAP_MOVEMENT              40093
#define IDM_CONST_UPDATE                40094
#define IDM_HARDWARE_CURSOR             40095
#define IDM_SPECTATOR_MODE              40096
#define IDM_COMMAND_TRACKING            40097
#define IDM_FIX_CP                      40098
#define IDS_DISABLED                    61729

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         40099
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
