#ifndef RUSEKEYS_H
#define RUSEKEYS_H
//------------------------------------------------------------------------//
/*
	Header file generated by the HotKey editor (jy)
	Original data file: D:\win32\Conquest\Src\RuseKeys.utf

	$Header: /Conquest/App/Src/RuseKeys.h 2     5/13/99 11:34a Jasony $
*/
//------------------------------------------------------------------------//

#ifdef _ADB

namespace RUSEKEYS
{
enum HOTKEY
{
	NONE,
	IDH_ACCEPT,
	IDH_DELETE,
	IDH_GROW_SYSTEM,
	IDH_LINK,
	IDH_LOAD,
	IDH_NEW,
	IDH_NEW_SYSTEM,
	IDH_SAVE,
	IDH_SHRINK_SYSTEM,
	IDH_ZOOM_IN,
	IDH_ZOOM_OUT
}; // enum HOTKEY
}  // namespace

#else  // !_ADB

#define IDH_ACCEPT                              0x00000001
#define IDH_DELETE                              0x00000002
#define IDH_GROW_SYSTEM                         0x00000003
#define IDH_LINK                                0x00000004
#define IDH_LOAD                                0x00000005
#define IDH_NEW                                 0x00000006
#define IDH_NEW_SYSTEM                          0x00000007
#define IDH_SAVE                                0x00000008
#define IDH_SHRINK_SYSTEM                       0x00000009
#define IDH_ZOOM_IN                             0x0000000A
#define IDH_ZOOM_OUT                            0x0000000B

#endif      // _ADB 

#endif
