//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mantis_T.rc
//
#define IDS_SOLTRAIN_MISSION_DESC       1
#define IDS_MT_DESC                     1
#define IDS_SOLTRAIN_MISSION_NAME       2
#define IDS_MT_NAME                     2
#define IDS_SOLTRAIN_STAD01             3
#define IDS_SOLTRAIN_STMG02             4
#define IDS_SOLTRAIN_STMG03             5
#define IDS_SOLTRAIN_TELETYPE_LOCATION  6
#define IDS_MT_TELETYPE_LOCATION        6
#define IDS_SOLTRAIN_STMG04             7
#define IDS_SOLTRAIN_STMG05             8
#define IDS_SOLTRAIN_STMG06             9
#define IDS_SOLTRAIN_STMG07             10
#define IDS_SOLTRAIN_STMG08             11
#define IDS_SOLTRAIN_STMG09             12
#define IDS_SOLTRAIN_STMG10             13
#define IDS_SOLTRAIN_STMG11             14
#define IDS_SOLTRAIN_STMG12             15
#define IDS_SOLTRAIN_STMG13             16
#define IDS_SOLTRAIN_STMG14             17
#define IDS_SOLTRAIN_STMG15             18
#define IDS_SOLTRAIN_STMG16             19
#define IDS_SOLTRAIN_STMG17             20
#define IDS_SOLTRAIN_STMG18             21
#define IDS_SOLTRAIN_STMG19             22
#define IDS_SOLTRAIN_STMG20             23
#define IDS_SOLTRAIN_STMG21             24
#define IDS_SOLTRAIN_STMG22             25
#define IDS_SOLTRAIN_STMG23             26
#define IDS_SOLTRAIN_STMG24             27
#define IDS_SOLTRAIN_STMG25             28
#define IDS_SOLTRAIN_STMG26             29
#define IDS_SOLTRAIN_STMG27             30
#define IDS_SOLTRAIN_STMG28             31
#define IDS_SOLTRAIN_STMG29             32
#define IDS_SOLTRAIN_STMG30             33
#define IDS_SOLTRAIN_STMG31             34
#define IDS_SOLTRAIN_STMG32             35
#define IDS_SOLTRAIN_STMG33             36
#define IDS_SOLTRAIN_STMG34             37
#define IDS_SOLTRAIN_STMG35             38
#define IDS_SOLTRAIN_STMG36             39
#define IDS_SOLTRAIN_STMG37             40
#define IDS_SOLTRAIN_STMG38             41
#define IDS_SOLTRAIN_STMG39             42
#define IDS_SOLTRAIN_MISSION_SUCCESS    43
#define IDS_SOLTRAIN_MISSION_FAILURE    44
#define IDS_MT_BEGIN                    45
#define IDS_MT_OBJECTIVE1               46
#define IDS_MT_OBJECTIVE2               47
#define IDS_MT_OBJECTIVE3               48
#define IDS_MT_OBJECTIVE4               49
#define IDS_MT_OBJECTIVE5               50
#define IDS_MT_OBJECTIVE6               51
#define IDS_MT_OBJECTIVE7               52
#define IDS_MT_OBJECTIVE8               53
#define IDS_MT_OBJECTIVE9               54
#define IDS_MT_OBJECTIVE10              55
#define IDS_MT_OBJECTIVE11              56
#define IDS_MT_OBJECTIVE12              57
#define IDS_MT_OBJECTIVE13              58
#define IDS_MT_OBJECTIVE14              59
#define IDS_MT_OBJECTIVE15              60
#define IDS_MT_OBJECTIVE16              61
#define IDS_MT_OBJECTIVE17              62
#define IDS_MT_OBJECTIVE18              63
#define IDS_MT_OBJECTIVE19              64
#define IDS_MT_OBJECTIVE20              65
#define IDS_MT_OBJECTIVE21              66
#define IDS_MT_FINAL                    67
#define IDS_MT_MISSION_SUCCESS          68
#define IDS_MT_MISSION_FAILURE          69
#define IDS_MT_OBJECTIVE12a             70
#define IDS_MT_OBJECTIVE19a             71
#define IDS_MT_OBJECTIVE19b             72
#define IDS_MT_OBJECTIVE20b             73
#define IDS_MT_ENEMY_NAME               74
#define IDS_MT_SUB_PROLOG17             75
#define IDS_MT_SUB_MTMD03               76
#define IDS_MT_SUB_MTMD04               77
#define IDS_MT_SUB_MTMD05               78
#define IDS_MT_SUB_MTMD06               79
#define IDS_MT_SUB_MTMD07               80
#define IDS_MT_SUB_MTMD08               81
#define IDS_MT_SUB_MTMD09               82
#define IDS_MT_SUB_MTMD10               83
#define IDS_MT_SUB_MTMD11               84
#define IDS_MT_SUB_MTMD12A              85
#define IDS_MT_SUB_MTMD13A              86
#define IDS_MT_SUB_MTMD32               87
#define IDS_MT_SUB_MTMD14               88
#define IDS_MT_SUB_MTMD15               89
#define IDS_MT_SUB_MTMD16               90
#define IDS_MT_SUB_MTMD17               91
#define IDS_MT_SUB_MTMD18A              92
#define IDS_MT_SUB_MTMD19               93
#define IDS_MT_SUB_MTMD20               94
#define IDS_MT_SUB_MTMD21               95
#define IDS_MT_SUB_MTMD21A              96
#define IDS_MT_SUB_MTMD21B              97
#define IDS_MT_SUB_MTMD22               98
#define IDS_MT_SUB_MTMD23               99
#define IDS_MT_SUB_MTMD24               100
#define IDR_PARSER_1                    101
#define IDS_MT_SUB_MTMD25               101
#define IDS_MT_SUB_MTMD26               102
#define IDS_MT_SUB_MTMD27               103
#define IDS_MT_SUB_MTMD28               104
#define IDS_MT_SUB_MTMD33               105
#define IDS_MT_SUB_MTMD30A              106
#define IDS_MT_SUB_MTMD34A              107
#define IDS_MT_SUB_MTMD34               108
#define IDS_MT_SUB_MTMD35               109
#define IDS_MT_SUB_MTMD36               110
#define IDS_MT_SUB_MTMD37               111

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
