#ifndef HOTKEYS_H
#define HOTKEYS_H
//------------------------------------------------------------------------//
/*
	Header file generated by the HotKey editor (jy)
	Original data file: Z:\CQ2\Code\App\Src\Hotkeys.utf

	$Header: /Libs/dev/Src/Tools/HotkeyEditor/Hklists.cpp 10    3/21/00 4:30p Pbleisch $
*/
//------------------------------------------------------------------------//

#ifdef _ADB

namespace HOTKEYS
{
enum HOTKEY
{
	NONE,
	IDH_ADMIRAL_TACTIC_DEFEND,
	IDH_ADMIRAL_TACTIC_HOLD,
	IDH_ADMIRAL_TACTIC_PEACE,
	IDH_ADMIRAL_TACTIC_SEEK,
	IDH_BUILD_PLATS,
	IDH_CANCEL_COMMAND,
	IDH_CENTER_SCREEN,
	IDH_CHATALL,
	IDH_CHATTEAM,
	IDH_CHAT_MENU,
	IDH_CLOAK,
	IDH_CONTEXT_A,
	IDH_CONTEXT_B,
	IDH_CONTEXT_C,
	IDH_CONTEXT_D,
	IDH_CONTEXT_E,
	IDH_CONTEXT_F,
	IDH_CONTEXT_G,
	IDH_CONTEXT_H,
	IDH_CONTEXT_I,
	IDH_CONTEXT_J,
	IDH_CONTEXT_K,
	IDH_CONTEXT_L,
	IDH_CONTEXT_M,
	IDH_CONTEXT_N,
	IDH_CONTEXT_O,
	IDH_CONTEXT_P,
	IDH_CONTEXT_Q,
	IDH_CONTEXT_R,
	IDH_CONTEXT_S,
	IDH_CONTEXT_T,
	IDH_CONTEXT_U,
	IDH_CONTEXT_V,
	IDH_CONTEXT_W,
	IDH_CONTEXT_X,
	IDH_CONTEXT_Y,
	IDH_CONTEXT_Z,
	IDH_CYCLE_ADMIRALS,
	IDH_CYCLE_FLEETS,
	IDH_DEBUG_PRINT,
	IDH_DEFEND,
	IDH_DESTROY,
	IDH_DIPLOMACY,
	IDH_DISBAND_FLEET,
	IDH_EJECT_ARTIFACT,
	IDH_FABRICATOR,
	IDH_FIGHTER_NORMAL,
	IDH_FIGHTER_PATROL,
	IDH_FLEET_GROUP_1,
	IDH_FLEET_GROUP_2,
	IDH_FLEET_GROUP_3,
	IDH_FLEET_GROUP_4,
	IDH_FLEET_GROUP_5,
	IDH_FLEET_GROUP_6,
	IDH_FLEET_SET_GROUP_1,
	IDH_FLEET_SET_GROUP_2,
	IDH_FLEET_SET_GROUP_3,
	IDH_FLEET_SET_GROUP_4,
	IDH_FLEET_SET_GROUP_5,
	IDH_FLEET_SET_GROUP_6,
	IDH_FLEET_SPORDER_0,
	IDH_FLEET_SPORDER_1,
	IDH_FLEET_SPORDER_10,
	IDH_FLEET_SPORDER_11,
	IDH_FLEET_SPORDER_2,
	IDH_FLEET_SPORDER_3,
	IDH_FLEET_SPORDER_4,
	IDH_FLEET_SPORDER_5,
	IDH_FLEET_SPORDER_6,
	IDH_FLEET_SPORDER_7,
	IDH_FLEET_SPORDER_8,
	IDH_FLEET_SPORDER_9,
	IDH_FORMATION_1,
	IDH_FORMATION_2,
	IDH_FORMATION_3,
	IDH_FORMATION_4,
	IDH_FORMATION_5,
	IDH_FORMATION_6,
	IDH_FORM_FLEET,
	IDH_FULLSCREEN_MAP,
	IDH_GAME_OPTIONS,
	IDH_GROUP_0_CREATE,
	IDH_GROUP_0_SELECT,
	IDH_GROUP_1_CREATE,
	IDH_GROUP_1_SELECT,
	IDH_GROUP_2_CREATE,
	IDH_GROUP_2_SELECT,
	IDH_GROUP_3_CREATE,
	IDH_GROUP_3_SELECT,
	IDH_GROUP_4_CREATE,
	IDH_GROUP_4_SELECT,
	IDH_GROUP_5_CREATE,
	IDH_GROUP_5_SELECT,
	IDH_GROUP_6_CREATE,
	IDH_GROUP_6_SELECT,
	IDH_GROUP_7_CREATE,
	IDH_GROUP_7_SELECT,
	IDH_GROUP_8_CREATE,
	IDH_GROUP_8_SELECT,
	IDH_GROUP_9_CREATE,
	IDH_GROUP_9_SELECT,
	IDH_HARVEST_STANCE_GAS,
	IDH_HARVEST_STANCE_NONE,
	IDH_HARVEST_STANCE_ORE,
	IDH_LOAD_MENU,
	IDH_MISSION_OBJ,
	IDH_MULTIPLAYER_SCORE,
	IDH_NEXT_UNIT,
	IDH_PATROL,
	IDH_PAUSE_GAME,
	IDH_PREV_UNIT,
	IDH_QUICK_LOAD,
	IDH_QUICK_SAVE,
	IDH_RALLY_POINT,
	IDH_RECORD_SPEECH,
	IDH_REPAIR,
	IDH_REPAIR_FLEET,
	IDH_REPORT_STATS,
	IDH_RESEARCH_PLAT,
	IDH_RESUPPLY_FLEET,
	IDH_RES_KIT_0,
	IDH_RES_KIT_1,
	IDH_RES_KIT_10,
	IDH_RES_KIT_11,
	IDH_RES_KIT_12,
	IDH_RES_KIT_13,
	IDH_RES_KIT_2,
	IDH_RES_KIT_3,
	IDH_RES_KIT_4,
	IDH_RES_KIT_5,
	IDH_RES_KIT_6,
	IDH_RES_KIT_7,
	IDH_RES_KIT_8,
	IDH_RES_KIT_9,
	IDH_ROTATE_0_WORLD,
	IDH_ROTATE_90_WORLD_LEFT,
	IDH_ROTATE_90_WORLD_RIGHT,
	IDH_ROTATE_WORLD_LEFT,
	IDH_ROTATE_WORLD_RIGHT,
	IDH_SAVE_MENU,
	IDH_SCREEN_SHOT,
	IDH_SCRIPT_KEY_1,
	IDH_SCRIPT_KEY_2,
	IDH_SCRIPT_KEY_3,
	IDH_SCRIPT_KEY_4,
	IDH_SCRIPT_KEY_5,
	IDH_SCROLL_DOWN,
	IDH_SCROLL_DOWNLEFT,
	IDH_SCROLL_DOWNRIGHT,
	IDH_SCROLL_LEFT,
	IDH_SCROLL_RIGHT,
	IDH_SCROLL_UP,
	IDH_SCROLL_UPLEFT,
	IDH_SCROLL_UPRIGHT,
	IDH_SEEK_EVENT,
	IDH_SELECT_ALL_FLEET,
	IDH_SELECT_IDLE_CIVILIAN,
	IDH_SELECT_IDLE_MILITARY,
	IDH_SELL,
	IDH_SPECIAL_ABILITY,
	IDH_SPECIAL_ABILITY1,
	IDH_SPECIAL_ABILITY2,
	IDH_SPECIAL_AEGIS,
	IDH_SPECIAL_ASSAULT,
	IDH_SPECIAL_AUGER,
	IDH_SPECIAL_BOMBER,
	IDH_SPECIAL_CLOAK,
	IDH_SPECIAL_DESTABILIZER,
	IDH_SPECIAL_FURYRAM,
	IDH_SPECIAL_MASSDISRUPT,
	IDH_SPECIAL_MIMIC,
	IDH_SPECIAL_MINELAYER,
	IDH_SPECIAL_PROBE,
	IDH_SPECIAL_PROTEUSMINE,
	IDH_SPECIAL_REPEL,
	IDH_SPECIAL_REPULSOR,
	IDH_SPECIAL_SHROUD,
	IDH_SPECIAL_STASIS,
	IDH_SPECIAL_SYNTHESIS,
	IDH_SPECIAL_TEMPEST,
	IDH_SPECIAL_VAMPIRE,
	IDH_SPECIAL_WORMHOLE,
	IDH_STANCE_ATTACK,
	IDH_STANCE_DEFENSIVE,
	IDH_STANCE_IDLE,
	IDH_STANCE_STANDGROUND,
	IDH_SUPPLY_STANCE_FULLYAUTO,
	IDH_SUPPLY_STANCE_NOAUTO,
	IDH_SUPPLY_STANCE_RESUPPLY,
	IDH_TARGET_POSITION,
	IDH_TEST_SPEECH,
	IDH_TOGGLE_SCREENMODE,
	IDH_TOGGLE_TOOLBAR,
	IDH_TOGGLE_ZOOM,
	IDH_TRANSFER_FLAGSHIP,
	IDH_USE_ARTIFACT,
	IDH_WIN_CLOSE,
	IDH_ZOOM_IN,
	IDH_ZOOM_OUT
}; // enum HOTKEY
}  // namespace

#else  // !_ADB

#define IDH_ADMIRAL_TACTIC_DEFEND               0x00000001
#define IDH_ADMIRAL_TACTIC_HOLD                 0x00000002
#define IDH_ADMIRAL_TACTIC_PEACE                0x00000003
#define IDH_ADMIRAL_TACTIC_SEEK                 0x00000004
#define IDH_BUILD_PLATS                         0x00000005
#define IDH_CANCEL_COMMAND                      0x00000006
#define IDH_CENTER_SCREEN                       0x00000007
#define IDH_CHATALL                             0x00000008
#define IDH_CHATTEAM                            0x00000009
#define IDH_CHAT_MENU                           0x0000000A
#define IDH_CLOAK                               0x0000000B
#define IDH_CONTEXT_A                           0x0000000C
#define IDH_CONTEXT_B                           0x0000000D
#define IDH_CONTEXT_C                           0x0000000E
#define IDH_CONTEXT_D                           0x0000000F
#define IDH_CONTEXT_E                           0x00000010
#define IDH_CONTEXT_F                           0x00000011
#define IDH_CONTEXT_G                           0x00000012
#define IDH_CONTEXT_H                           0x00000013
#define IDH_CONTEXT_I                           0x00000014
#define IDH_CONTEXT_J                           0x00000015
#define IDH_CONTEXT_K                           0x00000016
#define IDH_CONTEXT_L                           0x00000017
#define IDH_CONTEXT_M                           0x00000018
#define IDH_CONTEXT_N                           0x00000019
#define IDH_CONTEXT_O                           0x0000001A
#define IDH_CONTEXT_P                           0x0000001B
#define IDH_CONTEXT_Q                           0x0000001C
#define IDH_CONTEXT_R                           0x0000001D
#define IDH_CONTEXT_S                           0x0000001E
#define IDH_CONTEXT_T                           0x0000001F
#define IDH_CONTEXT_U                           0x00000020
#define IDH_CONTEXT_V                           0x00000021
#define IDH_CONTEXT_W                           0x00000022
#define IDH_CONTEXT_X                           0x00000023
#define IDH_CONTEXT_Y                           0x00000024
#define IDH_CONTEXT_Z                           0x00000025
#define IDH_CYCLE_ADMIRALS                      0x00000026
#define IDH_CYCLE_FLEETS                        0x00000027
#define IDH_DEBUG_PRINT                         0x00000028
#define IDH_DEFEND                              0x00000029
#define IDH_DESTROY                             0x0000002A
#define IDH_DIPLOMACY                           0x0000002B
#define IDH_DISBAND_FLEET                       0x0000002C
#define IDH_EJECT_ARTIFACT                      0x0000002D
#define IDH_FABRICATOR                          0x0000002E
#define IDH_FIGHTER_NORMAL                      0x0000002F
#define IDH_FIGHTER_PATROL                      0x00000030
#define IDH_FLEET_GROUP_1                       0x00000031
#define IDH_FLEET_GROUP_2                       0x00000032
#define IDH_FLEET_GROUP_3                       0x00000033
#define IDH_FLEET_GROUP_4                       0x00000034
#define IDH_FLEET_GROUP_5                       0x00000035
#define IDH_FLEET_GROUP_6                       0x00000036
#define IDH_FLEET_SET_GROUP_1                   0x00000037
#define IDH_FLEET_SET_GROUP_2                   0x00000038
#define IDH_FLEET_SET_GROUP_3                   0x00000039
#define IDH_FLEET_SET_GROUP_4                   0x0000003A
#define IDH_FLEET_SET_GROUP_5                   0x0000003B
#define IDH_FLEET_SET_GROUP_6                   0x0000003C
#define IDH_FLEET_SPORDER_0                     0x0000003D
#define IDH_FLEET_SPORDER_1                     0x0000003E
#define IDH_FLEET_SPORDER_10                    0x0000003F
#define IDH_FLEET_SPORDER_11                    0x00000040
#define IDH_FLEET_SPORDER_2                     0x00000041
#define IDH_FLEET_SPORDER_3                     0x00000042
#define IDH_FLEET_SPORDER_4                     0x00000043
#define IDH_FLEET_SPORDER_5                     0x00000044
#define IDH_FLEET_SPORDER_6                     0x00000045
#define IDH_FLEET_SPORDER_7                     0x00000046
#define IDH_FLEET_SPORDER_8                     0x00000047
#define IDH_FLEET_SPORDER_9                     0x00000048
#define IDH_FORMATION_1                         0x00000049
#define IDH_FORMATION_2                         0x0000004A
#define IDH_FORMATION_3                         0x0000004B
#define IDH_FORMATION_4                         0x0000004C
#define IDH_FORMATION_5                         0x0000004D
#define IDH_FORMATION_6                         0x0000004E
#define IDH_FORM_FLEET                          0x0000004F
#define IDH_FULLSCREEN_MAP                      0x00000050
#define IDH_GAME_OPTIONS                        0x00000051
#define IDH_GROUP_0_CREATE                      0x00000052
#define IDH_GROUP_0_SELECT                      0x00000053
#define IDH_GROUP_1_CREATE                      0x00000054
#define IDH_GROUP_1_SELECT                      0x00000055
#define IDH_GROUP_2_CREATE                      0x00000056
#define IDH_GROUP_2_SELECT                      0x00000057
#define IDH_GROUP_3_CREATE                      0x00000058
#define IDH_GROUP_3_SELECT                      0x00000059
#define IDH_GROUP_4_CREATE                      0x0000005A
#define IDH_GROUP_4_SELECT                      0x0000005B
#define IDH_GROUP_5_CREATE                      0x0000005C
#define IDH_GROUP_5_SELECT                      0x0000005D
#define IDH_GROUP_6_CREATE                      0x0000005E
#define IDH_GROUP_6_SELECT                      0x0000005F
#define IDH_GROUP_7_CREATE                      0x00000060
#define IDH_GROUP_7_SELECT                      0x00000061
#define IDH_GROUP_8_CREATE                      0x00000062
#define IDH_GROUP_8_SELECT                      0x00000063
#define IDH_GROUP_9_CREATE                      0x00000064
#define IDH_GROUP_9_SELECT                      0x00000065
#define IDH_HARVEST_STANCE_GAS                  0x00000066
#define IDH_HARVEST_STANCE_NONE                 0x00000067
#define IDH_HARVEST_STANCE_ORE                  0x00000068
#define IDH_LOAD_MENU                           0x00000069
#define IDH_MISSION_OBJ                         0x0000006A
#define IDH_MULTIPLAYER_SCORE                   0x0000006B
#define IDH_NEXT_UNIT                           0x0000006C
#define IDH_PATROL                              0x0000006D
#define IDH_PAUSE_GAME                          0x0000006E
#define IDH_PREV_UNIT                           0x0000006F
#define IDH_QUICK_LOAD                          0x00000070
#define IDH_QUICK_SAVE                          0x00000071
#define IDH_RALLY_POINT                         0x00000072
#define IDH_RECORD_SPEECH                       0x00000073
#define IDH_REPAIR                              0x00000074
#define IDH_REPAIR_FLEET                        0x00000075
#define IDH_REPORT_STATS                        0x00000076
#define IDH_RESEARCH_PLAT                       0x00000077
#define IDH_RESUPPLY_FLEET                      0x00000078
#define IDH_RES_KIT_0                           0x00000079
#define IDH_RES_KIT_1                           0x0000007A
#define IDH_RES_KIT_10                          0x0000007B
#define IDH_RES_KIT_11                          0x0000007C
#define IDH_RES_KIT_12                          0x0000007D
#define IDH_RES_KIT_13                          0x0000007E
#define IDH_RES_KIT_2                           0x0000007F
#define IDH_RES_KIT_3                           0x00000080
#define IDH_RES_KIT_4                           0x00000081
#define IDH_RES_KIT_5                           0x00000082
#define IDH_RES_KIT_6                           0x00000083
#define IDH_RES_KIT_7                           0x00000084
#define IDH_RES_KIT_8                           0x00000085
#define IDH_RES_KIT_9                           0x00000086
#define IDH_ROTATE_0_WORLD                      0x00000087
#define IDH_ROTATE_90_WORLD_LEFT                0x00000088
#define IDH_ROTATE_90_WORLD_RIGHT               0x00000089
#define IDH_ROTATE_WORLD_LEFT                   0x0000008A
#define IDH_ROTATE_WORLD_RIGHT                  0x0000008B
#define IDH_SAVE_MENU                           0x0000008C
#define IDH_SCREEN_SHOT                         0x0000008D
#define IDH_SCRIPT_KEY_1                        0x0000008E
#define IDH_SCRIPT_KEY_2                        0x0000008F
#define IDH_SCRIPT_KEY_3                        0x00000090
#define IDH_SCRIPT_KEY_4                        0x00000091
#define IDH_SCRIPT_KEY_5                        0x00000092
#define IDH_SCROLL_DOWN                         0x00000093
#define IDH_SCROLL_DOWNLEFT                     0x00000094
#define IDH_SCROLL_DOWNRIGHT                    0x00000095
#define IDH_SCROLL_LEFT                         0x00000096
#define IDH_SCROLL_RIGHT                        0x00000097
#define IDH_SCROLL_UP                           0x00000098
#define IDH_SCROLL_UPLEFT                       0x00000099
#define IDH_SCROLL_UPRIGHT                      0x0000009A
#define IDH_SEEK_EVENT                          0x0000009B
#define IDH_SELECT_ALL_FLEET                    0x0000009C
#define IDH_SELECT_IDLE_CIVILIAN                0x0000009D
#define IDH_SELECT_IDLE_MILITARY                0x0000009E
#define IDH_SELL                                0x0000009F
#define IDH_SPECIAL_ABILITY                     0x000000A0
#define IDH_SPECIAL_ABILITY1                    0x000000A1
#define IDH_SPECIAL_ABILITY2                    0x000000A2
#define IDH_SPECIAL_AEGIS                       0x000000A3
#define IDH_SPECIAL_ASSAULT                     0x000000A4
#define IDH_SPECIAL_AUGER                       0x000000A5
#define IDH_SPECIAL_BOMBER                      0x000000A6
#define IDH_SPECIAL_CLOAK                       0x000000A7
#define IDH_SPECIAL_DESTABILIZER                0x000000A8
#define IDH_SPECIAL_FURYRAM                     0x000000A9
#define IDH_SPECIAL_MASSDISRUPT                 0x000000AA
#define IDH_SPECIAL_MIMIC                       0x000000AB
#define IDH_SPECIAL_MINELAYER                   0x000000AC
#define IDH_SPECIAL_PROBE                       0x000000AD
#define IDH_SPECIAL_PROTEUSMINE                 0x000000AE
#define IDH_SPECIAL_REPEL                       0x000000AF
#define IDH_SPECIAL_REPULSOR                    0x000000B0
#define IDH_SPECIAL_SHROUD                      0x000000B1
#define IDH_SPECIAL_STASIS                      0x000000B2
#define IDH_SPECIAL_SYNTHESIS                   0x000000B3
#define IDH_SPECIAL_TEMPEST                     0x000000B4
#define IDH_SPECIAL_VAMPIRE                     0x000000B5
#define IDH_SPECIAL_WORMHOLE                    0x000000B6
#define IDH_STANCE_ATTACK                       0x000000B7
#define IDH_STANCE_DEFENSIVE                    0x000000B8
#define IDH_STANCE_IDLE                         0x000000B9
#define IDH_STANCE_STANDGROUND                  0x000000BA
#define IDH_SUPPLY_STANCE_FULLYAUTO             0x000000BB
#define IDH_SUPPLY_STANCE_NOAUTO                0x000000BC
#define IDH_SUPPLY_STANCE_RESUPPLY              0x000000BD
#define IDH_TARGET_POSITION                     0x000000BE
#define IDH_TEST_SPEECH                         0x000000BF
#define IDH_TOGGLE_SCREENMODE                   0x000000C0
#define IDH_TOGGLE_TOOLBAR                      0x000000C1
#define IDH_TOGGLE_ZOOM                         0x000000C2
#define IDH_TRANSFER_FLAGSHIP                   0x000000C3
#define IDH_USE_ARTIFACT                        0x000000C4
#define IDH_WIN_CLOSE                           0x000000C5
#define IDH_ZOOM_IN                             0x000000C6
#define IDH_ZOOM_OUT                            0x000000C7

#endif      // _ADB 

#endif
