

#ifndef _DA_D3DTYPES_H_
#define _DA_D3DTYPES_H_
#define _DA_D3DTYPES_H_

//

#include <d3d9.h>
#include <d3dx9.h> // Extension methods, needs the SDK
//#include <d3d9types.h>

//

#include "typedefs.h"

//

struct USING_INVALID_RENDERSTATE {
	U32 val;
};

//

struct USING_RENAMED_RENDERSTATE {
	U32 val;
};

//

#define D3DRS_TEXTUREHANDLE				((USING_INVALID_RENDERSTATE)0)
#define D3DRS_TEXTUREADDRESS				((USING_INVALID_RENDERSTATE)0)     
#define D3DRS_WRAPU						((USING_INVALID_RENDERSTATE)0)              
#define D3DRS_WRAPV						((USING_INVALID_RENDERSTATE)0)              
#define D3DRS_MONOENABLE					((USING_INVALID_RENDERSTATE)0)         
#define D3DRS_ROP2							((USING_INVALID_RENDERSTATE)0)               
#define D3DRS_PLANEMASK					((USING_INVALID_RENDERSTATE)0)          
#define D3DRS_TEXTUREMAG					((USING_INVALID_RENDERSTATE)0)         
#define D3DRS_TEXTUREMIN					((USING_INVALID_RENDERSTATE)0)         
#define D3DRS_TEXTUREMAPBLEND				((USING_INVALID_RENDERSTATE)0)    
#define D3DRS_SUBPIXEL						((USING_INVALID_RENDERSTATE)0)           
#define D3DRS_SUBPIXELX					((USING_INVALID_RENDERSTATE)0)          
#define D3DRS_STIPPLEENABLE				((USING_INVALID_RENDERSTATE)0)      
#define D3DRS_BORDERCOLOR					((USING_INVALID_RENDERSTATE)0)        
#define D3DRS_TEXTUREADDRESSU				((USING_INVALID_RENDERSTATE)0)    
#define D3DRS_TEXTUREADDRESSV				((USING_INVALID_RENDERSTATE)0)    
#define D3DRS_MIPMAPLODBIAS				((USING_INVALID_RENDERSTATE)0)      
#define D3DRS_ANISOTROPY					((USING_INVALID_RENDERSTATE)0)         
#define D3DRS_FLUSHBATCH					((USING_INVALID_RENDERSTATE)0)         
#define D3DRS_TRANSLUCENTSORTINDEPENDENT	((USING_INVALID_RENDERSTATE)0)
#define D3DRS_STIPPLEPATTERN00				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN01				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN02				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN03				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN04				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN05				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN06				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN07				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN08				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN09				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN10				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN11				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN12				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN13				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN14				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN15				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN16				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN17				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN18				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN19				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN20				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN21				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN22				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN23				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN24				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN25				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN26				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN27				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN28				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN29				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN30				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_STIPPLEPATTERN31				((USING_INVALID_RENDERSTATE)0)   
#define D3DRS_FOGTABLESTART				((USING_RENAMED_RENDERSTATE)0)      
#define D3DRS_FOGTABLEEND					((USING_RENAMED_RENDERSTATE)0)        
#define D3DRS_FOGTABLEDENSITY				((USING_RENAMED_RENDERSTATE)0)    
#define D3DRS_PERSPECTIVE					((USING_RENAMED_RENDERSTATE)0)    

//

const U32 D3DRS_MAX_STATE	= D3DRS_BLENDOPALPHA + 1;
const U32 D3DTSS_MAX_STATE			= D3DTSS_CONSTANT + 1;
const U32 D3DTSS_NUM_STAGES			=4;

#endif /* _DA_D3DTYPES_H_ */

